<div class="messageBox">
	<form method="post">
		<input type="hidden" name="action" value="add">
		
		<label>
			<span><?=__('Bestuursnaam:') ?></span>
			<input type="text" name="naam" placeholder="Bestuur XXII">
		</label>

		<label>
			<span><?=__('Sorteernaam:') ?></span>
			<input type="text" name="login" placeholder="bestuur22">
		</label>

		<input type="submit" class="button" value="<?=__('Bestuur toevoegen') ?>">
			
	</form>
</div>