<div class="timeline-container">
	<div class="timeline-line"></div>
	<div class="timeline">
		<div class="timeline-event has-header">
			<div class="messageBox">
				<?php
					$editable = new ControllerEditable('Oudbesturenpagina');
					$editable->run();
				?>
			</div>
		</div>
	<?php foreach ($iter as $bestuur): ?>
		<?php $editable = new ControllerEditable($bestuur->get('page')) ?>
		<div class="bestuur timeline-event has-header">
			<h1><?=$editable->get_title()?></h1>
			<div class="messageBox">
				<?php if ($editable->user_can_update()): ?>
					<a href="<?=markup_format_attribute($editable->link_to_update())?>"><?=__('Update')?></a>
				<?php endif ?>
				<?php
					ob_start();
					$editable->run();
					$html = ob_get_clean();

					echo $this->parse_bestuursfoto($bestuur, $html);
				?>
			</div>
		</div>
	<?php endforeach ?>

	<div class="timeline-event full-width">
		<div class="messageBox">
			<?php
				$editable = new ControllerEditable('Oprichting Cover');
				$editable->run();
			?>
		</div>
	</div>

	<?php if (member_in_commissie(COMMISSIE_BESTUUR)): ?>
		<div class="timeline-footer">
			<a href="besturen.php?add_bestuur" class="add-new-bestuur button"><?=__('Nieuw bestuur toevoegen...')?></a>
		</div>
	<?php endif ?>
	</div>
</div>
