<div class="timeline-container">
	<div class="timeline-line"></div>
	<div class="timeline">
		<div class="timeline-event has-header">
			<?php
				$editable = new ControllerEditable('Oudbesturenpagina');
				$editable->run();
			?>
		</div>
	<?php foreach ($iter as $bestuur): ?>
		<div class="bestuur timeline-event has-header">
			<?= $this->parse_bestuursfoto($bestuur, $pages[$bestuur->get('id')]) ?>
		</div>
	<?php endforeach ?>

	<div class="timeline-event full-width">
		<div class="messageBox">
			<p>XX-XX-19XX: Cover werd opgericht.</p>
		</div>
	</div>

	<?php if (member_in_commissie(COMMISSIE_BESTUUR)): ?>
		<div class="timeline-footer">
			<a href="besturen.php?add_bestuur" class="add-new-bestuur"><?=__('Nieuw bestuur toevoegen...')?></a>
		</div>
	<?php endif ?>
	</div>
</div>