<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, user-scalable=no">
		<title><?= $this->render_title() ?></title>
		<style>
			@media (max-width: 700px) {
				#page, #main-cell {
					width: auto !important;
				}
			}

			@media (max-width: 500px) {
				#page, #sidebar-cell, #main-cell {
					display: block;
					width: auto !important;
				}
			}
			
			img { max-width: 100%; }

			#sidebar-cell a {
				color:#FFFFFF;
			}

			#main-cell h2, #main-cell h3, #main-cell h4 {
				color: #C60C30;
			}
		</style>
	</head>
	<body style="margin:0; padding:0; font: 13px/16px sans-serif;">
		<!-- container -->
		<table style="border-collapse:collapse; height:100% !important; margin:0; padding:0; width:100% !important;" width="100%">
			<tr>
				<td bgcolor="#3B3B3B">
					<!-- table with sidebar and main section -->
					<center>
						<p style="color:white">Is the newsletter unreadable? <a href="<?=$this->render_permalink()?>" style="color:white;text-decoration:underline">Read the newsletter in your web browser</a>.</p>
						<table id="page" style="border-collapse:collapse;" width="700" cellspacing="0" cellpadding="20">
							<tr>
								<!-- Sidebar -->
								<td bgcolor="#C60C30" width="200" valign="top" id="sidebar-cell" class="mailing-sidebar">
									<table style="border-collapse:collapse; color:white" cellspacing="0" cellpadding="0" class="sidebar">
										<!-- logo -->
										<tr>
											<td height="60"><a href="<?=link_site()?>"><img style="border:0; height:auto; line-height:100%; outline:none; text-decoration:none;" alt="Cover logo" width="180" height="60" class="logo" src="<?=link_site('themes/default/images/cover_logo.png')?>"></a></td>
										</tr>

										<?php foreach ($this->sidebar as $section): ?>
										<tr>
											<td id="<?=$section->id()?>" class="mailing-editable">
												<?= $this->style_links($section->render()) ?>
											</td>
										</tr>
										<?php endforeach ?>

									</table>
								</td>

								<!-- Main -->
								<td bgcolor="#FFFFFF" valign="top" id="main-cell" class="mailing-main">
									<table style="border-collapse:collapse;" cellspacing="0" cellpadding="0">
										<!-- Titel -->
										<tr>
											<td height="60"><h1>Newsletter</h1></td>
										</tr>

										<?php foreach ($this->main as $section): ?>
										<tr>
											<td id="<?=$section->id()?>" class="mailing-editable">
												<?= $this->style_headers($section->render()) ?>
											</td>
										</tr>
										<?php endforeach ?>

										<tr>
											<td height="40" style="border-top: 1px solid #ccc;">
												<center>
													<p><small style="font-size: 9px">To cancel your registration to this mailing list please send an e-mail to <a href="mailto:administratie@svcover.nl">administratie@svcover.nl</a>.</small></p>
												</center>
											</td>
										</tr>
									</table>
								</td>
							</tr>
						</table>

						<br>

						<img alt="Fin." src="<?=link_site('images/bestuurxxii-white-88x100.png')?>" width="44" height="50">
					</center>
				</td>
			</tr>
		</table>
	</body>
</html>