<table>
	<tr>
		<td><?= label(__('Naam'), 'naam', $errors, true) ?> :</td>
		<td><?= input_text('naam', $data) ?></td>
	</tr>
	<tr>
		<td><?= label(__('Adres'), 'adres', $errors, true) ?>:</td>
		<td><?= input_text('adres', $data) ?></td>
	</tr>
	<tr>
		<td><?= label(__('Postcode'), 'postcode', $errors, true) ?>:</td>
		<td><?= input_text('postcode', $data) ?></td>
	</tr>
	<tr>
		<td><?= label(__('Plaats'), 'plaats', $errors, true) ?>:</td>
		<td><?= input_text('plaats', $data) ?></td>
	</tr>
	<tr>
		<td><?= label(__('Telefoon'), 'telefoonnummer', $errors, true) ?>:</td>
		<td><?= input_text('telefoonnummer', $data) ?></td>
	</tr>
	<tr>
		<td><?= label(__('Website'), 'plaats', $errors, true) ?>:</td>
		<td><?= input_text('website', $data) ?></td>
	</tr>
	<tr>
		<td><?= label(__('E-Mail'), 'email', $errors, false) ?>:</td>
		<td><?= input_text('email', $data) ?></td>
	</tr>
	<tr>
		<td><?= label(__('Contactpersoon'), 'contactpersoon', $errors, true) ?>:</td>
		<td><?= input_text('contactpersoon', $data) ?></td>
	</tr>
	<tr>
		<td colspan="2"><?= textarea_field('beschrijving', $data, $errors) ?></td>
	</tr>
	<tr class="submit">
		<td class="submit" colspan="2"><?= input_submit('subm', $data == null ? __('Bedrijf toevoegen') : 'Bedrijf wijzigen') ?></td>
	</tr>
</table>
