<div class="bar"><a href="javascript:beheer();"><?= image('add.png', '', __('Nieuw bedrijf toevoegen'), 'class="button"') ?></a> <a href="javascript:beheer();"><?= __('Nieuw bedrijf') ?></a></div>

<div id="bedrijvenBeheer" class="beheer">

<? if (isset($errors) && count($errors) > 0) { ?>
	<div class="error_message"><?= __('Niet alle velden zijn goed ingevuld') ?></div>
<? } ?>

<form method="post" action="afstudeerplaatsen.php#beheer">
	<?= input_hidden('submbedrijf_add', 'yes') ?>
	<? $this->render_partial('bedrijf_form', compact('errors')) ?>

</form>
</div>
<script type="text/javascript">
	function beheer() {
		div = document.getElementById("bedrijvenBeheer");

		if (div.style.display == "none" || div.style.display == "") {
			div.style.display = "block";
		} else {
			div.style.display = "none";
		}
	}

<? if (isset($expand)) {?>
	beheer();
<? } ?>
</script>
