<h1><?= __('Afstudeerplaatsen') ?></h1>
<div class="messageBox">
<? $admin = member_in_commissie(COMMISSIE_BESTUUR) || member_in_commissie(COMMISSIE_PRCIE);

if ($admin) 
	$this->render_partial('bedrijf_beheer', compact('model', 'iter', 'errors', 'data', 'expand')); // Niet zo cool dit.. misschien iets met instantievariabelen?

$email = $iter->get('email');
$website = $iter->get('website');

if ($website && strncmp($website, 'http://', 8) != 0)
	$website = 'http://' . $website;

if (strpos($email, '@') === false)
	$email = preg_replace('/_op_/i', '@', $email);
?>

<table class="default_noborder">
	<tr>
		<td><?= __('Naam') ?>:</td>
		<td><?= $iter->get('naam') ?></td>
	</tr>
	<tr>
		<td><?= __('Adres') ?>:</td>
		<td><?= $iter->get('adres') ?></td>
	</tr>
	<tr>
		<td><?= __('Postcode') ?>:</td>
		<td><?= $iter->get('postcode') ?></td>
	</tr>
	<tr>
		<td><?= __('Plaats') ?>:</td>
		<td><?= $iter->get('plaats') ?></td>
	</tr>
	<tr>
		<td><?= __('Telefoon') ?>:</td>
		<td><?= $iter->get('telefoonnummer') ?></td>
	</tr>
	<tr>
		<td><?= __('Website') ?>:</td>
		<td><?= $website ? ('<a href="' . $website . '">' . $website . '</a>')  : $website ?></td>
	</tr>
	<tr>
		<td><?= __('E-Mail') ?>:</td>
		<td><?= $email ? ('<a href="mailto:' . $email . '">' . $email . '</a>')  : $email ?></td>
	</tr>
	<tr>
		<td><?= __('Contactpersoon') ?>:</td>
		<td><?= $iter->get('contactpersoon') ?></td>
	</tr>
	<tr>
		<td><?= __('Beschrijving') ?>:</td>
		<td><?= markup_parse($iter->get('beschrijving')) ?></td>
	</tr>
</table>

<? $stages = $model->get_afstudeerplaatsen($iter->get_id());

if (count($stages) == 0)
	return;
 ?>
</div>
<div class="bar_sep"><h1><?= __('Concrete opdrachten') ?></h1></div>
<div class="messageBox">
<? foreach ($stages as $stage) {
	if ($admin) { ?>
		<div class="right">
			<a href="afstudeerplaatsen.php?editplaats=<?= $stage->get_id() ?>"><?= image('edit_small.png', __('Bewerken'), __('Bewerk bedrijf')) ?></a>
			<a href="afstudeerplaatsen.php?delplaats=<?= $stage->get_id() ?>" onClick="return verwijderen();"><?= image('delete_small.png', __('Verwijderen'), __('Verwijder bedrijf')) ?></a>
		</div>
	<h3><?= $stage->get('opdracht') ?></h3>
	<p><?= markup_parse($stage->get('beschrijving')) ?></p>
	<? } ?>
<? } ?>
</div>
<? if ($admin) { ?>
	<script type="text/javascript">
		function verwijderen() {
			return confirm("<?= __('Weet je zeker dat je deze afstudeerplaats wilt verwijderen?') ?>");
		}
	</script>
<? } ?>