<?
	$months = get_months();
	$days = get_days();
?>
<div class="newsHeading">

<?
$member_data = logged_in();

if (isset($forumid) && $member_data && count($member_data['commissies']) > 0)	{
?>
	<div class="controls inline"><a href="forum.php?forum=<?= $forumid ?>&startadd"><?= image('new.png', __('Toevoegen'), __('Een nieuwe mededeling toevoegen')) ?><?= __('Nieuwe mededeling') ?></a></div>
<? } ?>
<h1><?= __('Mededelingen') ?></h1></div>

<?
foreach ($iter as $item) {
	$message = $item->get_first_message();
	$author_info = $model->get_author_info($item);
	$link = get_author_link($item);
	echo '<hr class="colorAccent '. htmlspecialchars(strtolower($author_info['name']), ENT_QUOTES) .'" />';
	?>
	<div class="messageBox frontpage">
		<div class="newsTitle">
			<div class="right">
				<?= $item->get('datum') ?>
			</div>
			<span class="subject">
				<h3><?= markup_format_text($item->get('subject')) ?></h3>
			</span>
			<div class="subtitle">
				<?= __('Geplaatst door') ?>:
				<a href="<?=htmlspecialchars($link, ENT_QUOTES) ?>"><?= htmlspecialchars($author_info['name']) ?></a>
			</div>
		</div>
		<hr class="separator" />
		<div class="bericht">
			<?= markup_parse($message->get('message')) ?>
		</div>
	</div>
<?
}
?>
