<?php $editable = new ControllerEditable($iter) ?>
<div class="pageheading">
	<?php if($editable->user_can_update()): ?>
	<div class="controls inline">
		<a href="<?=markup_format_attribute($editable->link_to_update()) ?>"><?= image('edit.png', __('bewerken'), __('Pagina bewerken'))?></a>
	</div>
	<?php endif ?>
	<h1><?=markup_format_text($editable->get_title())?></h1>
</div>
<div class="messageBox"><?= $editable->run_embedded(); ?></div>
