<div class="newsHeading">
	<?php if ($model->member_can_create_announcements()): ?>
		<div class="controls inline"><a href="announcements.php"><?= image('new.png', __('Toevoegen'), __('Een nieuwe mededeling toevoegen')) ?><?= __('Nieuwe mededeling') ?></a></div>
	<?php endif ?>
	<h1><?= __('Mededelingen') ?></h1>
</div>

<?php foreach ($iter as $item): $committee = $item->getIter('committee'); ?>
	<hr class="colorAccent <?=$committee->get('login')?>">
	<div class="messageBox frontpage">
		<div class="newsTitle">
			<div class="right">
				<?= $item->get('created_on') ?>
			</div>
			<span class="subject">
				<h3><?= markup_format_text($item->get('subject')) ?></h3>
			</span>
			<div class="subtitle">
				<?= __('Geplaatst door') ?>:
				<a href="commissies.php?commissie=<?= rawurlencode($committee->get('login')) ?>"><?=markup_format_text($committee->get('naam'))?></a>
			</div>
		</div>
		<hr class="separator">
		<div class="bericht">
			<?= markup_parse($item->get('message')) ?>
		</div>
	</div>
<?php endforeach ?>
