<div class="messageBox">
	<h1><?=__('Mededeling toevoegen')?></h1>
	<form method="post" action="announcements.php?announcement_id=<?=$iter->get('id')?>" class="vertical-form">
		<div>
			<label for="field-committee"><?=__('Plaats namens commissie')?>:</label>
			<?=select_field('committee', $this->get_committee_options(), $iter->data)?>
		</div>

		<div>
			<label for="field-visibility"><?=__('Zichtbaar voor')?>:</label>
			<?=select_field('visibility', $this->get_visibility_options(), $iter->data)?>
		</div>		

		<div>
			<label for="field-subject"><?=__('Onderwerp')?>:</label>
			<?=input_text('subject', $iter->data, 'required', 'required')?>
		</div>

		<div>
			<label for="field-message"><?=__('Bericht')?>:</label>
			<?=textarea_field('message', $iter->data)?>
		</div>

		<div>
			<button type="submit" class="button"><?=__('Plaats mededeling')?></button>
		</div>
	</form>
</div>
