<h1><?=$this->get_label($iter, __('Nieuwe mededeling plaatsen'), __('Mededeling wijzigen')) ?></h1>
<div class="messageBox">
	<form method="post" action="<?=$this->get_form_action($iter)?>" class="vertical-form">
		<div>
			<?=label(__('Plaats namens commissie'), 'committee', $errors, true)?>
			<?=select_field('committee', $this->get_committee_options(), $iter->data)?>
		</div>

		<div>
			<?=label(__('Zichtbaar voor'), 'visibility', $errors, true)?>
			<?=select_field('visibility', $this->get_visibility_options(), $iter->data)?>
		</div>		

		<div>
			<?=label(__('Onderwerp'), 'subject', $errors, true)?>
			<?=input_text('subject', $iter->data, 'required', 'required')?>
		</div>

		<div>
			<?=label(__('Bericht'), 'message', $errors, true)?>
			<?=textarea_field('message', $iter->data)?>
		</div>

		<div>
			<button type="submit" class="button"><?=$this->get_label($iter, __('Plaats mededeling'), __('Wijzig mededeling')) ?></button>
		</div>
	</form>
</div>
