<h2><?= __('Vakken') ?></h2>
<div class="messageBox">

<?
$notebook = new Notebook('vakken');

$contents = $this->render_vakken($model, 1);
$notebook->add_page('1e jaar (' . $contents[1] . ')', $contents[0]);

$contents = $this->render_vakken($model, 2);
$notebook->add_page('2e jaar (' . $contents[1] . ')', $contents[0]);

$contents = $this->render_vakken($model, 3);
$notebook->add_page('3e jaar (' . $contents[1] . ')', $contents[0]);

$contents = $this->render_vakken($model, 4);
$notebook->add_page('4e jaar (' . $contents[1] . ')', $contents[0]);

$contents = $this->render_vakken($model, 5);
$notebook->add_page('5e jaar (' . $contents[1] . ')', $contents[0]);

$contents = $this->render_vakken($model, 0);
$notebook->add_page('Overige (' . $contents[1] . ')', $contents[0]);

echo $notebook->render();

$this->render_partial('nieuwe_documenten', compact('model'));
?>
</div>