<h1><?= __('Boeken bestellen')?></h1>
<div class="messageBox">
	<p>To order books with a 10% discount, you need to be a member of Cover.</p>
	<div class="call-to-action-or-block">
		<a href="lidworden.php" class="button"><?=__('Word lid')?></a>
		<span class="separator"><?=__('of')?></span>
		<a href="sessions.php?view=login&amp;referrer=boeken.php" data-placement-selector="modal" data-partial-selector="#login-form" class="button"><?=__('Log in')?></a>
	</div>
</div>