<form method="post" action="forum.php?thread=<?= $iter->get('id') ?>">
	<?= input_hidden('submforumpollvote', $iter->get('id')) ?>

	<table class="poll">
		<? foreach ($votes as $vote) {?>
		<tr>
			<td class="pollvoteRadio"><?= input_radio('optie', null, $vote->get_id(), 'id', $vote->get_id()) ?></td><td><label for="<? echo $vote -> get_id() ?>"><?= $vote->get('optie') ?></label></td>
		</tr>
		<? } ?>
	</table>

	<div class="poll_vote">
		<?= input_submit('subm', __('Stem'))  ?>
		<? if (isset($enable_new) && $enable_new) {?>
			<?= input_button(__('Nieuwe poll'), 'javascript:window.location = \'forum.php?forum=' . $iter->get('forum') . 'addpoll\'') ?>
		<? } ?>
	</div>
</form>
