	<div class="controls">
		<a href="fotoboek.php?book=<?=$iter->get_id()?>&amp;view=update_book" class="button"><?= image('edit.png', __('Bewerk'), __('Bewerk fotoboek aanmaken')) ?> <?= __('Bewerk fotoboek') ?></a>
		<a href="fotoboek.php?book=<?=$iter->get_id()?>&amp;view=add_book" class="button"><?= image('new.png', __('Nieuw'), __('Nieuw fotoboek aanmaken')) ?> <?= __('Nieuw fotoboek') ?></a>
		<a href="fotoboek.php?book=<?=$iter->get_id()?>&amp;view=add_photos" class="button"><?= image('add.png', __('Toevoegen'), __('Foto\'s toevoegen')) ?> <?= __('Foto\'s toevoegen') ?></a>
		<a id="delete-selected-photos-button" class="button photo-selection-control" href="#"><?= image('delete.png', __('Verwijderen'), __('Geselecteerde foto\'s verwijderen')) ?><?=__('Geselecteerde foto\'s verwijderen')?></a>
	</div>
	
	<script type="text/javascript">
		function sprintf(format)
		{
			for (var i = 1; i < arguments.length; ++i)
				format = format.replace(/\%d/, arguments[i]);

			return format;
		}

		$(function() {
			var checkboxes = $('.photos .thumbnail').map(function() {
				return $('<input type="checkbox">')
					.attr('name', 'photo[]')
					.val($(this).data('id'))
					.addClass('selection-checkbox photo-edit-control')
					.appendTo(this)
					.change(function() {
						updateSelectionControls();
					}).get();
			});

			var updateSelectionControls = function() {
				$('.photo-selection-control').toggle(
					checkboxes.is(':checked'));
			};

			$('#delete-selected-photos-button').click(function(e) {
				e.preventDefault();

				var selection = checkboxes.filter(':checked').map(function() {
					return this.value;
				});

				if (!confirm(sprintf(<?=json_encode(__('Weet je zeker dat je %d geselecteerde foto\'s wilt verwijderen?'))?>, selection.length)))
					return;

				var $form = $('<form>', {
					'method': 'post',
					'action': 'fotoboek.php?book=<?=$iter->get_id()?>&view=delete_photos'
				}).appendTo(document.body);

				$.each(selection, function(i, id) {
					$('<input>', {
						'type': 'hidden',
						'name': 'photo[]',
						'value': id
					}).appendTo($form);
				});
				
				$form.submit();
			});

			updateSelectionControls();
		});
	</script>
	
