<?php
$policy = get_policy($model);

// Filter the invisible books and reindex the array (required for the for-loops below.)
$children = array_values(array_filter($model->get_children($iter), array($policy, 'user_can_read')));

$collage_size = $iter ? 'small' : 'large';

if (!$children || count($children) == 0)
	return;
?>
<ul class="books">
	<?php foreach ($children as $book): ?>
	<?php
		$details = array();

		if ($book->get('num_books') > 0)
			$details[] = sprintf(_ngettext('%d boek', '%d boeken', $book->get('num_books')), $book->get('num_books'));

		if ($book->get('num_photos') > 0)
			$details[] = sprintf(_ngettext('%d foto', '%d foto\'s', $book->get('num_photos')), $book->get('num_photos'));
	?>		
	<li>
		<a href="fotoboek.php?book=<?=$book->get_id()?>" class="thumbnail <?=$collage_size?>">
			<div class="collage">
				<?php foreach ($model->get_photos_recursive($book, $collage_size == 'small' ? 4 : 9, true) as $photo): ?>
				<div class="image <?=image_aspect($photo->get_thumb_size())?>">
					<img src="<?=markup_format_attribute($photo->get('thumburl'))?>">
				</div>
				<?php endforeach ?>
			</div>
			<span class="title"><?=markup_format_text($book->get('titel'))?></span>
			<span class="details"><?=implode_human($details)?></span>
		</a>
	</li>
	<?php endforeach ?>
</ul>
