<?
if(logged_in() != false) { // laat alleen de reacties zien als er is ingelogd
	$reactie_model = get_model('DataModelFotoboekReacties');
	$reacties = $reactie_model->get_latest(15);
?>
<div class="bar_sep"><?= __('Laatste reacties') ?></div>

<?
	foreach ($reacties as $reactie) {
		$subtitle = true;
		// TODO let this be rendered by the FotoboekReactieController
		$this->render_partial('reactie', compact('reactie', 'subtitle'));
	}
}
?>
