<?php
if (!$iter)
	return;

$policy = get_policy($model);
?>
<div class="bar">
	<table class="navigation">
		<tr>
			<td>
			<?php if (($prev = $iter->get_previous_book()) && $policy->user_can_read($prev)): ?>
				<a href="fotoboek.php?book=<?=$prev->get_id()?>">
					<i class="fa fa-arrow-circle-o-left"></i>
					<?=markup_format_text($prev->get('titel')) ?>
				</a>
			<?php endif ?>
			</td>
			<td>
			<?php if (($parent = $iter->get_parent()) && $policy->user_can_read($parent)): ?>
				<a href="fotoboek.php?book=<?=$parent->get_id()?>">
					<i class="fa fa-arrow-circle-o-up"></i>
					<?=markup_format_text($parent->get('titel')) ?>
				</a>
			<?php endif ?>
			</td>
			<td>
			<?php if (($next = $iter->get_next_book()) && $policy->user_can_read($next)): ?>
				<a href="fotoboek.php?book=<?=$next->get_id() ?>">
					<?=markup_format_text($next->get('titel')) ?>
					<i class="fa fa-arrow-circle-o-right"></i>
				</a>
			<?php endif ?>
			</td>
		</tr>
	</table>
</div>
