<? if (member_in_commissie(COMMISSIE_FOTOCIE)) { ?>
	<div class="foto_titel"><form method="post" action="fotoboek.php?photo=<?= $iter->get('id') ?>">
	<?= input_hidden('submfotobeschrijving', 'yes') ?>
	<?= input_text('beschrijving', $iter->data) . ' ' . input_submit('subm', __('Opslaan')) ?>
	</form></div>
<? } elseif ($iter->get('beschrijving')) { ?>
	<div class="foto_titel"><?= htmlspecialchars($iter->get('beschrijving')) ?></div>
<? } ?>

<div id="foto" class="fotoboek_foto">

<?php if ($prev = $model->get_previous_photo($iter)): ?>
	<div class="prevPhoto">
		<a href="fotoboek.php?photo=<?= $prev->get('id') ?>#photo<?=$prev->get('id')?>">
			<span><?= __('Vorige') ?></span>
		</a>
	</div>
<? endif ?>

<?php if ($next = $model->get_next_photo($iter)): ?>
	<div class="nextPhoto">
		<a href="fotoboek.php?photo=<?= $next->get('id') ?>#photo<?=$next->get('id')?>">
			<span><?= __('Volgende') ?></span>
		</a>
	</div>
<?php endif ?>

<img id="photo" src="<?=markup_format_attribute($iter->get('url')) ?>">

</div>
<script type = "text/javascript">
	$(document).ready(function(){
		$(document).on('keyup.nav',function(event){keyPress(event);});
		$("textarea[name='reactie']").focus(function(){$(document).off('keyup.nav')}).blur(function(){$(document).on('keyup.nav', function(event){keyPress(event);})});
	});
	
	function keyPress(event)
	{
		if(event.keyCode == 37 && $(".prevPhoto > a").attr("href") != undefined)
			window.location.href = $(".prevPhoto > a").attr("href");
		else if (event.keyCode == 39 && $(".nextPhoto > a").attr("href") != undefined)
			window.location.href = $(".nextPhoto > a").attr("href");
		else if (event.keyCode == 38)
			window.location.href = $(".fotoboek_path_current > a").attr("href");
	}
</script>
