<?php
	$faces = get_model('DataModelFotoboekFaces')->get_for_photo($iter);
	
	// Filter out all the faces that cannot be identified by this user (because they are not allowed to)
	$faces = array_filter($faces, [get_policy('DataModelFotoboekFaces'), 'user_can_read']);

	$faces = array_map(function($face) {
		if ($face->has('lid_id'))
			return sprintf('<a href="profiel.php?lid=%d" data-face-id="%d" class="name">%s</a>',
				$face->getIter('lid')->get_id(),
				$face->get_id(),
				markup_format_text(member_full_name($face->getIter('lid'), BE_PERSONAL)));
		elseif ($face->has('custom_label'))
			return sprintf('<span class="custom-label" data-face-id="%d">%s</span>',
				$face->get_id(),
				markup_format_text($face['custom_label']));
		else
			return null; // Don't do anything with empty tags
	}, $faces);

	$faces = array_filter($faces); // Filter out the empty tags

if (count($faces))
	printf('<p class="photo-faces">%s</p>',
		sprintf(__('A photo with %s'), implode_human($faces)));