<?php
$photos = $iter->get_photos();

$like_model = get_model('DataModelFotoboekLikes');
$likes = $like_model->count_for_photos($photos);
$my_likes = logged_in()
	? $like_model->get_for_lid(logged_in_member(), $photos)
	: array();

$visibility = array();

if ($iter instanceof DataIterFacesPhotobook
	&& in_array(logged_in('id'), $iter->get('member_ids')))
{
	$privacy_model = get_model('DataModelFotoboekPrivacy');
	$visibility = $privacy_model->get_visibility_for_photos($photos, logged_in_member());
}

$classnames = function($photo) use ($my_likes, $visibility) {
	$classes = array();

	if (isset($my_likes[$photo->get_id()]))
		$classes[] = 'liked';

	if (isset($visibility[$photo->get_id()]) && !$visibility[$photo->get_id()])
		$classes[] = 'hidden';

	return $classes;
};

if (!$photos || count($photos) == 0)
	return;
?>
<ul class="photos flow-gallery">
	<!-- add the 'grid-gallery' class for awesomeness -->
	<?php foreach ($photos as $photo): ?>
	<li id="photo_<?=$photo->get_id()?>" data-id="<?=$photo->get_id()?>" class="thumbnail <?=implode(' ', $classnames($photo))?>">
		<a href="fotoboek.php?book=<?=$iter->get_id()?>&amp;photo=<?=$photo->get_id()?>#a">
			<img src="<?=markup_format_attribute($photo->get_url(null, 400))?>" <?=($size = $photo->get_scaled_size(null, 400)) ? vsprintf('width="%d" height="%d"', $size) : ''?>>
			<?php if (isset($likes[$photo->get_id()])): ?>
				<span class="like-button" title="<?=markup_format_attribute(sprintf(_ngettext('%d lid vindt deze foto awesome', '%d leden vinden deze foto awesome', $likes[$photo->get_id()]), $likes[$photo->get_id()]))?>"><?=$likes[$photo->get_id()]?></span>
			<?php endif ?>
			<?php if (isset($visibility[$photo->get_id()]) && !$visibility[$photo->get_id()]): ?>
			<span class="privacy"><?=__('Verborgen voor anderen')?></span>
			<?php endif ?>
			<?php if ($photo->get('num_reacties') > 0): ?>
			<span class="comments"><?=markup_format_text(sprintf(_ngettext('%d reactie', '%d reacties', $photo->get('num_reacties')), $photo->get('num_reacties')))?></span>
			<?php endif ?>
			<?php if (strlen($photo->get('beschrijving')) > 0): ?>
			<span class="description"><?=markup_format_text($photo->get('beschrijving'))?></span>
			<?php endif ?>
		</a>
	</li>
	<?php endforeach ?>
</ul>

<script src="<?=get_theme_data('data/flowgallery.js')?>"></script>
<script>$('.photos.flow-gallery').flowgallery();</script>