<?
$photos_per_row = 3;
$photos = $model->get_photos($iter);

$admin = member_in_commissie(COMMISSIE_FOTOCIE);

if (!$photos || count($photos) == 0)
	return;
if ($admin) { ?>
	<form action="fotoboek.php?book=<?= ($iter ? $iter->get('id') : '') ?>" method="post" onSubmit="return confirm('<? str_replace("'", "\\'", __('Weet je zeker dat je de geselecteerde foto\'s wilt verwijderen?')) ?>');"><?= input_hidden('submfotoboekdelfotos', 'yes'); ?>
<? } ?>
	<table class="photobookPhotos">
		<tbody>
<?
for ($i = 0; $i < count($photos); $i += $photos_per_row) {
	$images = array();
	$titles = array();
	echo '<tr>';
	for ($n = $i; $n < $i + $photos_per_row; $n++) {
		if ($n >= count($photos)) {
			$images[] = '';
			$titles[] = '';
		} else {
			$photo = $photos[$n];
			$images[] = '<a id="photo_' . $photo->get('id') . '" href="fotoboek.php?photo=' . $photo->get('id') . '#a"><img src="' . htmlspecialchars($photo->get('thumburl'), ENT_QUOTES) . '"></a>';

			$title = htmlspecialchars($photo->get('beschrijving'));
			$num = $photo->get('num_reacties');
		
			if ($photo->get('reactie'))
				$title .= ($title ? '<br>' : '') . '(<span class="fotoboek_highlight">' . sprintf(_ngettext('%d reactie', '%d reacties', $num), $num) . '</span>)';

			if ($admin)
				$title = input_checkbox('del_' . $photo->get('id'), null) . ' ' . $title;

			$titles[] = $title;
		}
	}
	//echo the images in this row
	for ($idx = 0; $idx != $photos_per_row; ++$idx)
	{
		echo '
			<td class = "foto">
				'. $images[$idx] .'
				<p class = "fotoTitle">
					'. $titles[$idx] .'
				</p>
			</td>';
	}
	echo '</tr>';	
	?>
<? } ?>
		</tbody>
	</table>


<? if ($admin) { ?>
	<div class="text_right"><?= input_submit('subm', __('Geselecteerde foto\'s verwijderen')) ?></div></form>
<? } ?>
