<ol class="slides">
<?php foreach ($model->get_photos($iter) as $photo): ?>
	<li id="photo<?=$photo->get('id')?>" class="<?=$current->get('id') == $photo->get('id') ? 'current' : ''?> slide">
		<a href="fotoboek.php?photo=<?=$photo->get('id')?>#photo<?=$photo->get('id')?>">
			<img src="<?=markup_format_attribute($photo->get('thumburl'))?>" title="<?=markup_format_attribute($photo->get('beschrijving'))?>">
		</a>
	</li>
<?php endforeach ?>
</ol>
