<h1><?= __('Fotoboek') ?> :: <?= __("Foto's toevoegen") ?></h1>
<div class="messageBox">
	<?php $this->render_partial('path', array('model' => $model, 'book' => $iter, 'photo' => null)) ?>

	<div id="folder-selector"></div>

	<form action="fotoboek.php?book=<?= $iter->get_id() ?>&amp;view=add_photos" method="post">
		<ul id="photo-selector">
			<li>
				<img class="thumbnail">
				<span class="titel">
					<input type="text" name="photo[$i][titel]" placeholder="<?=__('Omschrijving')?>">
				</span>
				<span class="filename"></span>
				<span class="created-on"></span>
				<input type="hidden" name="photo[$i][path]">
			</li>
		</ul>
	</form>
</div>

<script>
var baseurl = 'fotoboek.php?book=<?=$iter->get_id()?>';

jQuery(function($) {
	function basename(path) {
		var match = path.match(/\/([^\/]+)$/);
		return match ? match[1] : path;
	}

	function load_folders(path, ol) {
		$.getJSON(baseurl + '&view=add_photos_list_folders&path=' + path).then(function(data) {
			$.each(data, function(index, folder) {
				$('<li>')
					.data('folder', folder)
					.text(basename(folder))
					.appendTo(ol);
			});
		});
	}

	var stream = null;

	function handle_stream_error(e) {
		if (e.readyState != EventSource.CLOSED) {
			console.error(e);
		} 
	}

	var $photo_template = $('#photo-selector li').detach();

	function load_photos(path, $ol) {
		if (stream)
			stream.close();

		var index = 0;

		stream = new EventSource(baseurl + '&view=add_photos_list_photos&path=' + path);
		stream.addEventListener('error', handle_stream_error);

		stream.addEventListener('end', function(e) {
			stream.close();
		});

		stream.addEventListener('photo', function(e) {
			var photo = JSON.parse(e.data);

			var $li = $photo_template.clone();
			$li.data('sort-order', Date.parse(photo['created_on'].replace(' ', 'T')));

			// Try to find a node of a photo taken after this one and insert this one before that
			$ol.find('li').each(function(i, li) {
				if ($(li).data('sort-order') > $li.data('sort-order')) {
					$li.insertBefore(li);
					return false;
				}
			});

			// If it hasn't been inserted by insertion sort, append it to the end.
			if (!$li.parent().length)
				$li.appendTo($ol);
				
			$li.find('.thumbnail')
				.attr('src', photo['thumbnail']);

			$li.find('.titel input')
				.attr('name', 'photo[' + index + '][titel]')
				.val(photo['titel']);
			
			$li.find('.filename')
				.text(basename(photo['path']))
				.attr('title', photo['path']);

			$li.find('.created-on')
				.text(photo['created_on']);

			$li.find('input[type=hidden]')
				.attr('name', 'photo[' + index + '][path]')
				.val(photo['path']);

			index++;
		}, false);
	}

	load_folders('', $('<ol>').appendTo('#folder-selector'));

	$('#folder-selector').on('click', 'li', function(e) {
		e.preventDefault();
		e.stopPropagation();

		$(this).parent('ol').find('li').removeClass('selected');
		$(this).addClass('selected');

		var ol = $(this).parent('ol').next('ol');
		if (ol.length)
			ol.empty();
		else
			ol = $('<ol>').insertAfter($(this).parent('ol'));

		load_folders($(this).data('folder'), ol);
		
		load_photos($(this).data('folder'), $('#photo-selector').empty());
	});
})
</script>
