<h1><?=__('Fotoboek verwijderen') ?></h1>
<div class="messageBox">
	<form method="post" action="fotoboek.php?view=delete_book&amp;book=<?=$iter->get_id()?>" class="vertical-form">
		<p><?=sprintf(__('Weet je heel zeker dat je het fotoboek <em>%s</em> wil verwijderen?'),
			markup_format_text($iter->get('titel')))?></p>
		<label for="confirm_delete"><?=__('Typ om dit fotoboek te verwijderen de naam van het fotoboek over ter bevestiging')?></label>
		<input type="text" name="confirm_delete" id="confirm_delete">
		<div>
			<button type="submit" class="button"><?=__('Verwijder fotoboek') ?></button>
			<a href="fotoboek.php?book=<?=$iter->get('parent')?>#book_<?=$iter->get_id()?>"><?=__('Terug naar fotoboek')?></a>
		</div>
	</form>
</div>
