<?php
$commissie_model = get_model('DataModelCommissie');
$leden = $commissie_model->get_leden($iter->get('id'));
?>
<div class="messageBox">
	<form action="actieveleden.php?commissie=<?= $iter->get('id') ?>" method="post">
		<?= input_hidden('submactieveledencommissie', 'yes') ?>
		<table class="default">
			<col class="text_center">
			<col>
			<col class="text_center">
			<col>
			<col>
			<tr class="header">
				<th class="text_center"><?= image('delete_small.png', __('D'), __('Verwijder actief lid')) ?></th>
				<th><?= __('Nr') ?></th>
				<th><?= __('Sleutel') ?></th>
				<th><?= __('Naam') ?></th>
				<th><?= __('Functie') ?></th>
			</tr>
			<?php if ($leden && count($leden) > 0): ?>
				<?php foreach ($leden as $lid): ?>
					<tr>
						<td class="text_center"><?= input_checkbox('del_' . $lid->get('actiefid'), null) ?></td>
						<td><?= $lid->get('id') ?></td>
						<td><?= input_checkbox('sleutel_' . $lid->get('actiefid'), $lid->data, 'yes', 'field', 'sleutel') ?></td>
						<td><?= htmlspecialchars(member_full_name($lid)) ?></td>
						<td><?= input_text('functie_' . $lid->get('actiefid'), $lid->data, 'field', 'functie') ?></td>
					</tr>
				<?php endforeach ?>
			<?php else: ?>
				<tr>
					<td colspan="5"><?= __('Deze commissie heeft nog geen leden') ?></td>
				</tr>
			<?php endif ?>
			<tr>
				<td class="text_center"><?= input_checkbox('vacancies', $iter->data, '1') ?></td>
				<td colspan="4">
					<?= label(__('Deze commissie zoekt nieuwe leden'), 'vacancies') ?>
				</td>
			</tr>
			<tr>
				<td colspan="5" class="submit"><?= input_submit('subm', __('Opslaan')) ?></td>
			</tr>
		</table>
	</form>
</div>
