<div class="messageBox">
<?php $this->render_partial('navigation', ['tab' => 'history']) ?>
<table id="membership-history" class="default">
	<col class="text_center">
	<col>
	<col class="text_center">
	<col>
	<col>
	<thead>
		<tr class="header">
			<th><?= __('Naam') ?></th>
			<th><?= __('Commissie') ?></th>
			<th><?= __('Functie') ?></th>
			<th><?= __('Ingehamerd op') ?></th>
			<th><?= __('Uitgehamerd op') ?></th>
		</tr>
	</thead>
	<tbody>
	<?php foreach ($model->get_membership_history() as $membership): ?>
			<tr data-membership-id="<?= $membership->get_id() ?>">
				<td><a href="profiel.php?lid=<?=$membership->getIter('lid')->get('id')?>"><?= markup_format_text(member_full_name($membership->getIter('lid'))) ?></a></td>
				<td><?= markup_format_text($membership->getIter('commissie')->get('naam')) ?></td>
				<td><?= markup_format_text($membership->get('functie')) ?></td>
				<td data-property-name="started_on"><?= $membership->get('started_on') ?></td>
				<td data-property-name="discharged_on"><?= $membership->get('discharged_on') ?></td>
			</tr>
	<?php endforeach ?>
	</tbody>
</table>
</div>		

<script>
jQuery(function($) {
	$('#membership-history tbody > tr[data-membership-id]').each(function(i, row) {
		//
	});
})
</script>
