<?php

// Create mask
$circle = new Imagick();
$circle->newImage($width, $width, 'none');
$circle->setimagematte(true);

// Draw the circle on the mask
$draw = new ImagickDraw();
$draw->setfillcolor('#000');
$draw->circle($width / 2, $width / 2, 2, $width / 2);
$circle->drawimage($draw);

// Load image and composite mask on top of it
$imagick = new Imagick();
$imagick->readImageBlob(pg_unescape_bytea($model->get_photo($iter)));
$imagick->scaleImage($width, 0);
$imagick->cropimage($width, $width, 0, 0);
$imagick->compositeimage($circle, Imagick::COMPOSITE_COPYOPACITY, 0, 0);

// Send proper headers: cache control & mime type
header('Pragma: public');
header('Cache-Control: max-age=86400');
header('Expires: '. gmdate('D, d M Y H:i:s \G\M\T', time() + 86400));
header('Content-Type: image/png');

// Write image to php output buffer
$out = fopen('php://output', 'w');
$imagick->setImageFormat('png');
$imagick->writeImageFile($out);

// And clean up.
fclose($out);
$imagick->destroy();
