<?php
$photo = $model->get_photo($iter);
header('Pragma: public');
header('Cache-Control: max-age=86400');
header('Expires: '. gmdate('D, d M Y H:i:s \G\M\T', time() + 86400));
header("Content-Type: image/png");

// Code from getthumb.php
$large = imagecreatefromstring(pg_unescape_bytea($photo));
// Thumbnail width
$th = 100 * imagesy($large) / imagesx($large);
$thumb = imagecreatetruecolor(100, $th);
//$thumb = imagecreate(100, $th);
imagecopyresampled($thumb, $large, 0, 0, 0, 0, 100, $th, imagesx($large), imagesy($large));
imagepng($thumb);
?>