<div class="messageBox">
	<form method="post" action="<?=markup_format_text($controller->link_to_delete($iter))?>" class="vertical-form">
		<p><?=sprintf(__('Weet je heel zeker dat je de reactie van <em>%s</em> wilt verwijderen?'),
			markup_format_text(member_full_name($iter->get('auteur'))))?></p>
		<div>
			<button type="submit" class="button"><?=__('Verwijder reactie') ?></button>
			<a href="<?=markup_format_text($controller->link_to_read($iter))?>"><?=__('Terug naar reacties')?></a>
		</div>
	</form>
</div>
