<div class="heading-with-controls">
	<h2><?= __('Reacties') ?></h2>
	<?php if (get_policy($model)->user_can_create()): ?>
	<a href="<?=markup_format_attribute($controller->link_to_create())?>" class="create-link" title="<?=markup_format_attribute(__('Een nieuwe reactie toevoegen'))?>" onclick="$('#fotoboek_reactie').toggle().find('textarea').focus(); return false"><?= __('Nieuwe reactie') ?></a>
	<?php else: ?>
		<p><?=preg_replace_callback('/\{\{(.+?)\}\}/',
			function($match) { return login_link(markup_format_text($match[1])); },
			markup_format_text(__('{{Log in}} om te kunnen reageren.'))) ?></p>
	<?php endif ?>
</div>

<?php if (get_policy($model)->user_can_create()): ?>
	<div id="fotoboek_reactie" class="beheer" <?php if (isset($errors) && in_array('reactie', $errors)) echo 'style="display:block"' ?>>
		<?php $this->form(array(
			'model' => $model,
			'controller' => $controller,
			'iter' => $empty_iter,
			'errors' => array())) ?>
	</div>
<?php endif ?>

<?php if (!$iter || count($iter) == 0): ?>
	<p><?= __('Er zijn nog geen reacties') ?></p>
<?php else: ?>
	<?php foreach ($iter as $reactie): ?>
		<?php $this->single(array('iter' => $reactie, 'model' => $model, 'controller' => $controller)) ?>
	<?php endforeach ?>
<?php endif ?>
