<?php
$days = get_days();
$months = get_months();
?>
<div class="replyBox comment" id="comment<?=$iter->get_id()?>">
	<div class="title">
		<span class="replyDetails">
			<div class="right">
				<span class="number-of-likes" <?=
					$iter['likes'] == 0
						? ''
						: sprintf(' title="%s"', 
							markup_format_attribute(
								sprintf(
									_ngettext('%s vindt dit leuk', '%s vinden dit leuk', $iter['likes']), 
									implode_human(
										array_map('member_first_name', $iter['liked_by'])
									)
								)
							)
						); ?>><?=__N('%d like', '%d likes', $iter['likes'])?></span>
				
				<span class="timestamp"><?= sprintf('%s %d %s, %02d:%02d', $days[$iter->get('dagnaam')], $iter->get('datum'), $months[$iter->get('maand')], $iter->get('uur'), $iter->get('minuut')) ?></span>
			</div>
			<?= markup_format_text(member_full_name($iter->get('auteur'), BE_PERSONAL)) ?>
		</span>
	</div>
	
	<div class="bericht">
		<?= markup_parse($iter->get('reactie')) ?>
	</div>

	<ul class="actions">
		<?php if (get_auth()->logged_in()): ?>
			<?php if ($iter->is_liked_by(get_identity()->get_member())): ?>
				<li>
					<form method="post"
						action="<?=markup_format_attribute($controller->link_to_like($iter))?>"
						data-partial-selector="#comment<?=$iter['id']?>"
						data-placement-selector="#comment<?=$iter['id']?>">
						<input type="hidden" name="action" value="unlike">
						<button type="submit" class="link comment-like-button">Unlike</button>
					</form>
				</li>
			<?php else: ?>
				<li>
					<form method="post"
						action="<?=markup_format_attribute($controller->link_to_like($iter))?>"
						data-partial-selector="#comment<?=$iter['id']?>"
						data-placement-selector="#comment<?=$iter['id']?>">
						<input type="hidden" name="action" value="like">
						<button type="submit" class="link comment-like-button">Like</button>
					</form>
				</li>
			<?php endif ?>
		<?php endif ?>
		<?php if (get_policy($model)->user_can_update($iter)): ?>
		<li><a href="<?=markup_format_attribute($controller->link_to_update($iter))?>"
			data-partial-selector=".replyBox"
			data-placement-selector=".replyBox"><?=__('Wijzig')?></a></li>
		<?php endif ?>
		<?php if (get_policy($model)->user_can_delete($iter)): ?>
		<li><a href="<?=markup_format_attribute($controller->link_to_delete($iter))?>"
			data-partial-selector=".replyBox"
			data-placement-selector=".replyBox"><?=__('Verwijder')?></a></li>
		<?php endif ?>
	</ul>
</div>
