<?
$commissie_model = get_model('DataModelCommissie');
$commissie = $commissie_model->get_iter($iter->get('commissie'));
?>
<!-- color accent for each 'commissie' -->
<h1><?= $iter->get('kop') ?></h1>
<hr class="colorAccent <? echo strtolower($commissie_model->get_naam($commissie->get('page')));?>">
<div class="messageBox">
<?php if ($cover_photo = $this->get_cover_photo($iter)): ?>
	<img src="<?=$cover_photo?>" class="event-cover-photo">
<?php endif ?>
<p><?= __('Datum & Tijd') ?>: <?= agenda_period_for_display($iter, 'van') ?><br/>
<? if ($iter->get('locatie')) { ?>
	<?= __('Locatie')?>: <?= markup_format_text($iter->get('locatie')) ?><br/>
<? } ?>
</p>
<p><?= markup_parse($iter->get('beschrijving')) ?></p>

<ul>
<?php foreach ($this->get_attending($iter) as $attendee): ?>
	<li>
		<img src="https://graph.facebook.com/<?=$attendee['id']?>/picture/?width=200&amp;height=200" style="border-radius: 50%; border: 1px solid #ccc;" width="100" height="100">
		<span class="name"><?=markup_format_text($attendee['name']) ?></span>
	</li>
<?php endforeach ?>
</ul>

<p><span class="smaller"><?= __('Geplaatst door') ?>: <a href="show.php?id=<?= $commissie->get('page') ?>"><?= htmlspecialchars($commissie->get('naam')) ?></a></span></p>
<p>
	<a href="agenda.php"><?= image('agenda.png', __('agenda'), __('Volledige agenda bekijken'), 'class="top"') ?> <?= __('Volledige agenda') ?></a>
	<?php if (member_in_commissie($iter->get('commissie')) || member_in_commissie(COMMISSIE_BESTUUR)): ?>
	- <a href="agenda.php?agenda_edit&amp;agenda_id=<?= $iter->get_id() ?>"><?= __('Wijzig') ?></a>
	- <a href="agenda.php?agenda_del&amp;agenda_id=<?= $iter->get_id() ?>" onClick="return confirm('<?= __('Weet je zeker dat je dit agendapunt wilt verwijderen?') ?>');"><?= __('Verwijder') ?></a>
	<?php endif ?>
</p>
</div>
