<h1><?= ($iter != null ? __('Wijzig agendapunt') : __('Agendapunt toevoegen')) ?></h1>
<div class="messageBox">
<? if (!empty($errors)) { 
	print_r($errors); ?>
	<p><span class="error"><?= __('Niet alle velden zijn goed ingevuld') ?></span></p>
<? 
} ?>
<form name="agenda_form" action="<?= get_request() ?>" method="post">
<h3><?= __('Algemene informatie'); ?></h3>
<table class="agenda_edit">
<col width="180px"><col width="20px"><col>
<?= input_hidden('submagenda', 'yes'); ?>

<? 
$data = ($iter != null ? $iter->data : null);
$member_data = logged_in();
$commissies = array();
$model = get_model('DataModelCommissie');

if ($data) {
	$data['use_tot'] = false;

	foreach (array('datum', 'maand', 'jaar', 'uur', 'minuut') as $check) {
		if ($data['van' . $check] != $data['tot' . $check]) {
			$data['use_tot'] = true;
			break;
		}
	}
}

if (member_in_commissie(COMMISSIE_BESTUUR) || member_in_commissie(COMMISSIE_KANDIBESTUUR))
	foreach ($model->get() as $commissie)
		$commissies[$commissie->get_id()] = $commissie->get('naam');
else
	foreach ($member_data['committees'] as $commissie)
		$commissies[$commissie] = $model->get_naam($commissie);
?>


<?= table_row(label(__('Titel'), 'kop', $errors, true) . ':', '', 
		input_text('kop', $data, 'maxlength', '100')) ?>
<?= table_row(label(__('Commissie'), 'commissie', $errors, true) . ':', '',
		select_field('commissie', $commissies, $data)) ?>

<?= table_row(label(__('Begintijd'), 'van', $errors, true) . ':', '', 
		input_date('vandatum', $data, 'class', 'agenda_date', 'placeholder', 'dd-mm-yyyy') . ' ' .
		input_time('vantijd', $data, 'class', 'agenda_time', 'placeholder', '--:--'))?>
<?= table_row(label(__('Eindtijd'), 'tot', $errors, false) . ' ('.__(optioneel).') :', '', 
		input_date('totdatum', $data, 'class', 'agenda_date', 'placeholder', 'dd-mm-yyyy') . ' ' .
		input_time('tottijd', $data, 'class', 'agenda_time', 'placeholder', '--:--') . 
		'</div>') ?>

<?= table_row(label(__('Locatie'), 'locatie', $errors, false) . ':', '', 
		input_text('locatie', $data, 'maxlength', '100')) ?>

		<tr>
			<td style="vertical-align: top;">
				<?= __('Beschrijving') . ':'; ?>
			</td>
			<td>
				<!-- empty td for styling purpose -->
			</td>
			<td>
				<?= textarea_field('beschrijving', $data, $errors, 'formatter', 'markup_format_text', 'cols', 50, 'rows', 7) ?>
			</td>
		</tr>
		<tr>
			<td class="just_a_bit_lower">
				<?= label(__('Alleen zichtbaar voor leden'), 'private', $errors, false) ?>
			</td>
			<td class="just_a_bit_lower">
				<!-- empty td for styling purpose -->
			</td>
			<td class="just_a_bit_lower">
				<?= input_checkbox('private', $data) ?>
			</td>
		</tr>
		<tr>
			<td class="just_a_bit_lower">
				<?= label(__('Introducées toegestaan'), 'guests_allowed', $errors, false) ?>
			</td>
			<td class="just_a_bit_lower">
				<!-- empty td for styling purpose -->
			</td>
			<td class="just_a_bit_lower">
				<?= input_checkbox('guests_allowed', $data) ?>
			</td>
		</tr>
		<tr>
			<td class="just_a_bit_lower">
				<?= label(__('Externe activiteit'), 'extern', $errors, false) ?>
			</td>
			<td class="just_a_bit_lower">
				<!-- empty td for styling purpose -->
			</td>
			<td class="just_a_bit_lower">
				<?= input_checkbox('extern', $data) ?>
			</td>
		</tr>
</table>
<br />
<h3 id="signupinfo"><?= __('Inschrijfinformatie'); ?></h3>
<table class="agenda_edit" id="signuptable">
<col width="180px"><col width="20px"><col>
<?= table_row(label(__('Prijs'), 'price', $errors, true) . ':', '', 
		input_text('price', $data, 'maxlength', '8', 'value', '€ ')) ?>
		
<?= table_row(label(__('Capaciteit'), 'participants_limit', $errors, true) . ':', '', 
		input_text('participants_limit', $data, 'maxlength', '8')) ?>
		

<?= table_row(label(__('Begin inschrijvingen'), 'signups_start', $errors, true) . ':', '', 
		input_date('signups_startdatum', $data, 'class', 'agenda_date', 'placeholder', 'dd-mm-yyyy') . ' ' .
		input_time('signups_starttijd', $data, 'class', 'agenda_time', 'placeholder', '--:--'))?>
		
<?= table_row(label(__('Deadline inschrijvingen'), 'signups_end', $errors, false) . ':', '',
		input_date('signups_enddatum', $data, 'class', 'agenda_date', 'placeholder', 'dd-mm-yyyy') . ' ' .
		input_time('signups_endtijd', $data, 'class', 'agenda_time', 'placeholder', '--:--') . 
		'</div>') ?>
</table>
<br />
<h3 id="socialmedia"><?= __('Social media'); ?></h3>
<table class="agenda_edit" id="socialmediatable">
<col width="180px"><col width="20px"><col>
<?= table_row(label(__('Facebook Event'), 'facebook_id', $errors, false) . ':', '',
		input_text('facebook_id', $data, 'size', '20')) ?>
</table>
<br />
<table class="agenda_edit">
<col width="180px"><col width="20px"><col>
		<tr>
			<td class="submit" colspan="3">
				<?= input_submit('subm', ($iter != null ? __('Wijzigen') : __('Toevoegen'))) ?>
			</td>
		</tr>
	</table>
</form>

<script type="text/javascript">

	jQuery('input[name=facebook_id]').change(function(e) {
		var expr = /^https:\/\/www\.facebook\.com\/events\/(\d+)\//;
		var match = $(this).val().match(expr);

		if (match)
			$(this).val(match[1]);
	});
	/*
	$( "#signupinfo" ).click(function() {
	  $( "#signuptable" ).toggle( );
	});
	$( "#socialmedia" ).click(function() {
	  $( "#socialmediatable" ).toggle( );
	}); */
</script>
</div>
