<h1><?= $this->get_title() ?></h1>
<div class="messageBox">	
<? if (!logged_in()) { ?>
	<p class="italic"><?= __('Log in om eventuele afgeschermde agendapunten te bekijken.') ?></p>
<? } else { ?>
	<div class="bar_right">
	
	<? if (($aantal = $model->has_moderate()) && member_in_commissie(COMMISSIE_BESTUUR)) {
		if ($aantal == 1)
			$s = __('Er staat nog 1 agendapunt in de wachtrij');
		else
			$s = sprintf(__('Er staan nog %d agendapunten in de wachtrij'), $aantal);

		?><div class="left"><a href="agenda.php?agenda_moderate"><?= $s ?></a></div>
	<? }
	
	$member = logged_in();
	$member_model = get_model('DataModelMember');

	if (count($member_model->get_commissies($member['id'])) > 0) { ?>
		<a href="agenda.php?agenda_add"><?= image('add.png', __('nieuw'), __('Nieuw agendapunt toevoegen')) ?></a>
	<? } ?>
	</div>
<? } ?>

<?php if (($prev_year = $this->get_previous_year()) !== null): ?>
<a href="agenda.php?year=<?=$prev_year?>" class="prev-year"><?printf(__('Toon alles uit het jaar %d-%d'), $prev_year, $prev_year + 1)?></a>
<?php endif ?>

<?php if (($next_year = $this->get_next_year()) !== null): ?>
<a href="agenda.php?year=<?=$next_year?>" class="next-year"><?printf(__('Toon alles uit het jaar %d-%d'), $next_year, $next_year + 1)?></a>
<?php endif ?>


<table class="agenda" style="background-color: #000;">

<?php 
if (!isset($iter))
	$iter = $this->get_paged_agendapunten();

$curmaand = -1;
$months = get_months();
$days = get_days();

if (!count($iter)) { ?>
	<p> <?= __('Er staan op dit moment geen activiteiten op de agenda.') ?></p>
<? }
foreach ($iter as $punt) {
	$date = strtotime($punt->get('van'));
	if ($curmaand != $punt->get('vanmaand')) { ?>
		</table>
		<h2>
			<?= $months[$punt->get('vanmaand')] ?>
			<?= isset($show_year) && $show_year ? $punt->get('vanjaar') : '' ?>
		</h2>
		<table class="agenda">
		
		<?
		$curmaand = $punt->get('vanmaand');
	} ?>
	
	<tr>
		<td class="vandatum">
			<div class="calendar-icon">
				<span class="month"><?=strftime('%b', $date)?></span>
				<span class="day"><?=strftime('%d', $date)?></span>
			</div>
		</td>
		<td><a class="agendalink" href="<?=markup_format_attribute($controller->link_to_read($punt))?>"><?= markup_format_text($punt->get('kop')) ?></a><br/>
		<?= agenda_period_for_display($punt) ?><br/>

	<? if ($punt->get('locatie')) { ?>
		<?= __('Locatie') ?>: <?= markup_format_text($punt->get('locatie')) ?><br/>
	<? }

	
			<ul class="actions">
				<?php if (get_policy($this->model)->user_can_delete($punt)): ?>
				<li><a href="<?=markup_format_attribute($controller->link_to_delete($punt))?>" onClick="return confirm('<?= __('Weet je zeker dat je dit agendapunt wilt verwijderen?') ?>');"><?= __('Verwijder') ?></a></li>
				<?php endif ?>
				<?php if (get_policy($this->model)->user_can_update($punt)): ?>
				<li><a href="<?=markup_format_attribute($controller->link_to_update($punt))?>"><?= __('Wijzig') ?></a></li>
				<?php endif ?>
			</ul>
		</td>
	</tr>
<? } ?>

</table>

<p><?=__('De Coveragenda is ook beschikbaar in verschillende standaarden:')?> 
<a href="agenda.php?format=webcal&amp;session_id=<?=session_get_application_session_id('calendar')?>">iCal (website)</a>, 
<a href="http://www.google.com/calendar/feeds/s16ii08dg06pt83j0mblbnqfrc%40group.calendar.google.com/public/basic">XML (gcal)</a>,
<a href="http://www.google.com/calendar/ical/s16ii08dg06pt83j0mblbnqfrc%40group.calendar.google.com/public/basic.ics">iCal (gcal)</a></p>
</div>
