<h1><?=markup_format_text($iter['naam'])?></h1>
<div class="messageBox">
	<?php $this->committee_view->render_partial('leden', compact('model', 'iter')) ?>

	<table class="full-width-table">
		<thead>
			<tr>
				<th><?=__('Datum')?></th>
				<th><?=__('Reden')?></th>
				<th><?=__('Punten')?></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($scores as $score): ?>
			<tr>
				<td><?=markup_format_text($score['awarded_on'])?></td>
				<td><?=markup_format_text($score['awarded_for'])?></td>
				<td><?=$score['points']?></td>
				<td>
					<?php if (get_policy($model)->user_can_update($score)): ?>
						<a href="<?=markup_format_attribute($controller->link_to_update($score)) ?>"><?=__('Bewerk')?></a>
					<?php endif ?>
					<?php if (get_policy($model)->user_can_delete($score)): ?>
						<a href="<?=markup_format_attribute($controller->link_to_delete($score)) ?>"><?=__('Verwijder')?></a>
					<?php endif ?>
				</td>
			</tr>
			<?php endforeach ?>
		</tbody>
	</table>
</div>