<h1><?=markup_format_text($iter['naam'])?></h1>
<div class="messageBox">
	<?php $this->committee_view->render_partial('leden', compact('model', 'iter')) ?>

	<table class="full-width-table">
		<thead>
			<tr>
				<th><?=__('Datum')?></th>
				<th><?=__('Reden')?></th>
				<th><?=__('Punten')?></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($scores as $score): ?>
			<tr>
				<td><?=markup_format_text(date_create_immutable($score['awarded_on'])->format('d-m-Y'))?></td>
				<td>
					<?=markup_format_text($score['awarded_for'])?>
					<ul class="inline-profile-list">
					<?php foreach ($score['members'] as $lid): ?>
						<li><a href="profiel.php?lid=<?=$lid->get('id')?>" class="committee-member">
							<img src="foto.php?lid_id=<?=$lid->get('id')?>&amp;format=square&amp;width=50" width="25">
							<span class="name"><?=markup_format_text(member_full_name($lid, BE_PERSONAL)) ?></span>
						</a></li>
					<?php endforeach ?>
					</ul>
				</td>
				<td><?=$score['points']?></td>
				<td>
					<?php if (get_policy($model)->user_can_update($score)): ?>
						<a href="<?=markup_format_attribute($controller->link_to_update($score)) ?>" class="button" data-placement-selector="modal" data-partial-selector=".committee-battle-form"><?=__('Bewerk')?></a>
					<?php endif ?>
					<?php if (get_policy($model)->user_can_delete($score)): ?>
						<a href="<?=markup_format_attribute($controller->link_to_delete($score)) ?>" class="button" data-placement-selector="modal" data-partial-selector=".committee-battle-form"><?=__('Verwijder')?></a>
					<?php endif ?>
				</td>
			</tr>
			<?php endforeach ?>
		</tbody>
	</table>
</div>