<h1><?=$this->get_label($iter, __('Nieuwe punten toekennen'), __('Punten wijzigen')) ?></h1>
<div class="messageBox">
	<form method="post" action="<?=markup_format_attribute($iter && $iter->has_id()
			? $this->controller->link_to_update($iter)
			: $this->controller->link_to_create($iter['committee'])) ?>" class="vertical-form committee-battle-form"">

		<fieldset>
			<legend><?=label(__('Leden'), 'member_ids[]', $errors, true)?></legend>
			<?=select_field('member_ids[]', $this->active_member_options(), $iter, 'field', 'member_ids', 'multiple', true)?>
		</fieldset>

		<fieldset>
			<legend><?=__('Commissies')?></legend>
			<ul class="option-group columns">
				<?php foreach ($this->committee_options() as $committee): ?>
				<li>
					<?=input_checkbox('committee_ids[]', $iter, $committee['id'], 'id', 'field-committee-' . $committee['id'], 'data-member-ids', implode(' ', (array_map(getter('id'), $committee['members']))))?>
					<?=label($committee['naam'], 'committee-' . $committee['id'])?>
				</li>
				<?php endforeach ?>
			</ul>
		</fieldset>

		<div>
			<?=label(__('Punten'), 'points', $errors, true)?>
			<?=_input_field('points', $iter, ['type' => 'number'])?>
		</div>
		<div>
			<?=label(__('Reden'), 'awarded_for', $errors, true)?>
			<?=textarea_field('awarded_for', $iter, $errors)?>
		</div>
		<div>
			<button type="submit" class="button"><?=$this->get_label($iter, __('Voeg punten toe'), __('Wijzig punten')) ?></button>
			<a href="<?=markup_format_text($controller->link_to_index())?>"><?=__('Terug naar het overzicht')?></a>
		</div>
	</form>
</div>
