<div class="messageBox">
	<form action="" method="post" class="vertical-form">
		<div>
			<?=label(__('Commissie'), 'committee_id', $errors, true)?>
			<?=select_field('committee_id', $this->committee_options(), $iter) ?>
		</div>
		<div>
			<?=label(__('Punten'), 'points', $errors, true)?>
			<?=_input_field('points', $iter, ['type' => 'number'])?>
		</div>
		<div>
			<button type="submit"><?=__('Opslaan')?></button>
		</div>
	</form>
</div>