<div class="messageBox committee-battle">
	<table class="full-width-table committee-battle-scores">
		<thead>
			<tr>
				<th><?=__('Commissie')?></th>
				<th><?=__('Punten')?></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($iter as $committee): ?>
			<tr>
				<td>
					<a href="<?=markup_format_attribute($controller->link_to_read($committee))?>"><?=markup_format_text($committee['naam'])?></a>
					<ul class="inline-member-list">
					<?php foreach ($committee['members'] as $lid): ?>
						<li><a href="profiel.php?lid=<?=$lid->get('id')?>" class="committee-member">
							<img src="foto.php?lid_id=<?=$lid->get('id')?>&amp;format=square&amp;width=50" width="25">
							<span class="name"><?=markup_format_text(member_full_name($lid, BE_PERSONAL)) ?></span>
						</a></li>
					<?php endforeach ?>
					</ul>
				</td>
				<td><?=$committee['score']?></td>
				<td><?php if (get_policy($model)->user_can_create()): ?>
					<a href="<?=markup_format_attribute($controller->link_to_create($committee)) ?>">Add</a><?php endif ?></td>
			</tr>
			<?php endforeach ?>
		</tbody>
	</table>
</div>