<?php
header('Content-Description: File Transfer');
header('Content-Type: application/force-download');
header('Content-Disposition: attachment; filename="almanak.csv"');

$delim = ','; // Used to be ';'

// Add Unicode byte order marker for Excel
echo chr(239) . chr(187) . chr(191);

// print the column headers
echo csv_row(array(
	__('id'),
	__('voornaam'),
	__('tussenvoegsel'),
	__('achternaam'),
	__('adres'),
	__('postcode'),
	__('woonplaats'),
	__('email'),
	__('geboortedatum'),
	__('geslacht'),
	__('telefoonnummer'),
	__('studie'),
	__('beginjaar'),
	__('status')), $delim) . "\n";

foreach ($iter as $item)
	echo csv_row(array(
		$item->get('id'),
		$item->get('voornaam'),
		$item->get('tussenvoegsel'),
		$item->get('achternaam'),
		$item->get('adres'),
		$item->get('postcode'),
		$item->get('woonplaats'),
		$item->get('email'),
		$item->get('geboortedatum'),
		$item->get('geslacht'),
		$item->get('telefoonnummer'),
		$item->get('studie'),
		$item->get('beginjaar'),
		$item->get('status')), $delim) . "\n";

exit();
