<div class="pageheading">
	<h1><?=__('Bedrijf toevoegen')?></h1>
</div>

<div class="messageBox">
	<form method="post" action="" enctype="multipart/form-data">
		<div>
			<?=label('Naam', 'naam', $errors, true)?>
			<?=input_text('naam', $data)?>
		</div>

		<div>
			<?=label('Website', 'website', $errors, true)?>
			<?=input_text('website', $data)?>
		</div>

		<div>
			<?=label('Logo', 'logo', $errors, true)?>
			<input type="file" name="logo" accept="image/*">
		</div>

		<div>
			<button type="submit"><?=__('Nieuw bedrijf toevoegen')?></button>
		</div>
	</form>
</div>
