<h1> <?= __('Bedrijven') ?></h1>
<div class="messageBox bedrijven-index">
<?php foreach ($iter as $bedrijf): ?>
	<?php $imgpath = $this->get_bedrijf_thumb($bedrijf); ?>
	<a class="bedrijf" href="bedrijfs.php?bedrijf=<?= rawurlencode($bedrijf->get('slug')) ?>" <?php if ($imgpath): ?>style="background-image: url(<?=$imgpath?>)"<?php endif?>>
		<span class="overlay">
			<span class="name"><?= htmlspecialchars($bedrijf->get('naam')) ?></span>
			<span class="summary"><?= $this->get_summary($bedrijf) ?></span>
		</span>
	</a>
<? endforeach ?>
</div>
