<div class="page-heading">
	<?php if (get_policy($model)->user_can_update($iter)): ?>
	<div class="controls inline">
		<a href="bedrijven.php?id=<?=rawurlencode($iter->get('slug'))?>&amp;view=update" id="edit-bedrijf-button">
			<img src="<?=get_theme_data('images/edit.png')?>" alt="<?=__('Aanpassen')?>">
			<?=__('Bedrijf aanpassen')?>
		</a>
	</div>
	<?php endif ?>
	<h1><?=markup_format_text($iter->get('naam'))?></h1>
</div>

<?php
$editable = new ControllerEditable($iter->get('page'));
$editable->run();
?>
