<h1><?= __('Mailinglijsten') ?></h1>
<div class="messageBox mailinglists">
<?php if (member_in_commissie(COMMISSIE_EASY)): ?>
	<a href="#new-list" class="button floatRight">
		<img src="themes/default/images/add.png">
		<?=__('Nieuwe mailinglijst')?>
	</a>

	<div id="new-list" class="section hide-by-default">
		<form method="post" class="vertical-form" action="mailinglijsten.php?lijst_id=">
			<div>
				<label for="adres"><?=__('Lijstadres') ?>:</label>
				<input id="adres" type="email" name="adres" placeholder="e.g. lijstnaam@svcover.nl">
			</div>
			<div class="inline-block">
				<label for="toegang"><?=__('Toegang')?>:</label>
				<?=select_field('toegang', $this->get_all_toegang_options(), null, 'id', 'toegang')?>
				<small><?=__('Wie mag e-mails sturen naar deze lijst?')?></small>
			</div>
			<div class="inline-block">
				<label for="commissie"><?=__('Commissie')?>:</label>
				<?=select_field('commissie', $this->get_all_commissies(), null, 'id', 'commissie') ?>
				<small><?=__('Welke commissie mag bepalen wie er op de lijst staat?')?></small>
			</div>
			<div>
				<label for="naam"><?=__('Naam') ?>:</label>
				<input id="naam" type="text" name="naam">
			</div>
			<div>
				<label for="omschrijving"><?=__('Omschrijving')?>:</label>
				<textarea id="omschrijving" name="omschrijving"></textarea>
			</div>
			<div>
				<input id="publiek" type="checkbox" name="publiek">
				<label for="publiek"><?=__('Mensen mogen zichzelf aanmelden voor deze lijst.')?></label>
			</div>
			<div class="controls">
				<button class="button" type="submit"><?=__('Maak lijst')?></button>
			</div>
		</form>
	</div>
<?php endif ?>

<?php foreach ($iter as $lijst): ?>
	<div class="mailinglist">
		<h3 class="list-name">
		<?php if ($model->member_can_edit($lijst)): ?>
		<a href="mailinglijsten.php?lijst_id=<?=$lijst->get('id')?>"><?= markup_format_text($lijst->get('naam')) ?></a>
		<?php else: ?>
		<?= markup_format_text($lijst->get('naam')) ?>
		<?php endif ?>
		</h3>

		<em class="list-email"><?= htmlspecialchars($lijst->get('adres')) ?></em>
		<?php if (!$lijst->get('publiek')): ?>
		<em class="list-public-status"><?=__('Verborgen')?></em>
		<?php endif ?>

		<p class="list-description"><?= markup_parse($lijst->get('omschrijving')) ?></p>
		<form method="post">
			<input type="hidden" name="mailinglijst_id" value="<?=$lijst->get('id')?>">
		<?php if ($lijst->get('abonnement_id')): ?>
			<input type="hidden" name="action" value="unsubscribe">
			<input type="hidden" name="abonnement_id" value="<?=$lijst->get('abonnement_id')?>">
			<p><input type="submit" class="button" value="<?=__('Uitschrijven')?>"> <?= $member->get('id') == logged_in('id') ? __('Je bent aangemeld voor deze mailinglijst.') : sprintf(__('%s is aangemeld voor deze mailinglijst.'), markup_format_text($member->get('voornaam'))) ?></p>
		<?php else: ?>
			<input type="hidden" name="action" value="subscribe">
			<input type="submit" class="button" value="<?=__('Aanmelden')?>">
		<?php endif ?>
		</form>
	</div>
<?php endforeach ?>
</div>