<h1><?=_('Mailinglijst')?> :: <?=markup_format_text($lijst->get('naam'))?></h1>
<div class="messageBox">
	<form method="post" action="mailinglijsten.php?lijst_id=<?=$lijst->get('id')?>">
	<ul>
	<?php foreach ($aanmeldingen as $aanmelding): ?>
		<li>
			<label>
				<input type="checkbox" name="unsubscribe[]" value="<?=$aanmelding->get('abonnement_id')?>">
				<?=htmlspecialchars($aanmelding->get('naam'))?>
				<em><?=htmlspecialchars($aanmelding->get('email'))?></em>
			</label>
		</li>
	<?php endforeach ?>
	</ul>
	<button class="button" type="submit"><?=__('Meld geselecteerde adressen af')?>
	</form>
</div>

<div class="messageBox">
	<form method="post" action="mailinglijsten.php?lijst_id=<?=$lijst->get('id')?>">
		<div>
			<label for="naam"><?=__('Naam') ?>:</label>
			<input id="naam" type="text" name="naam" value="<?=htmlspecialchars($lijst->get('naam'), ENT_QUOTES)?>">
		</div>
		<div>
			<label for="omschrijving"><?=__('Omschrijving') ?>:</label>
			<textarea id="omschrijving" name="omschrijving"><?=htmlspecialchars($lijst->get('omschrijving'))?></textarea>
		</div>
		<div>
			<input id="publiek" type="checkbox" name="publiek" <?php if ($lijst->get('publiek')) echo 'checked' ?>>
			<label for="publiek"><?=__('Mensen mogen zichzelf aanmelden voor deze lijst.')?></label>
		</div>
		<div class="controls">
			<button class="button" type="submit"><?=__('Update lijst')?></button>
		</div>
	</form>
</div>

<div class="messageBox">
	<form method="post" action="mailinglijsten.php?lijst_id=<?=$lijst->get('id')?>">
		<label for="lid_id"><?=__('Lidnummer(s)')?>:</label>
		<input type="text" id="lid_id" name="subscribe">
		<button type="submit" class="button"><?=__('Meld aan')?></button>
	</form>
</div>