<h1><?=_('Mailinglijst')?> :: <?=markup_format_text($lijst->get('naam'))?></h1>
<div class="messageBox">
	<form method="post" action="mailinglijsten.php?lijst_id=<?=$lijst->get('id')?>">
	<ul>
	<?php foreach ($aanmeldingen as $aanmelding): ?>
		<li>
			<label>
				<input type="checkbox" name="unsubscribe[]" value="<?=$aanmelding->get('abonnement_id')?>">
				<?=htmlspecialchars($aanmelding->get('naam'))?>
				<em><?=htmlspecialchars($aanmelding->get('email'))?></em>
			</label>
		</li>
	<?php endforeach ?>
	</ul>
	<button class="button" type="submit"><?=__('Meld geselecteerde adressen af')?>
	</form>
</div>