<div class="search-result-member">
	<h2>
		<a href="<?=markup_format_attribute($iter->get_absolute_url())?>">
			<?=member_full_name($iter, false, false) ?>
		</a>
	</h2>
	
	<div class="profile-widget">
		<img src="foto.php?lid_id=<?=$iter->get_id()?>&amp;format=square&amp;width=200" width="100" height="100">
	</div>

	<?php
	$rows = array();

	foreach (array('adres', 'email', 'telefoonnummer') as $field)
		if (!$iter->is_private($field))
			$rows[] = sprintf('<dt>%s</dt><dd>%s</dd>',
				__($field), markup_format_text($iter->get($field)));

	printf('<dl class="member">%s</dl>', implode("\r\n", $rows));
	?>
</div>