<h2>
	<a href="fotoboek.php?book=<?=$iter->get_id()?>"><?=markup_format_text($iter->get('titel'))?></a>
	<small><?=sprintf(__('Fotoboek in %s'),
		sprintf('<a href="fotoboek.php?book=%d">%s</a>',
			$iter->get_parent()->get_id(),
			markup_format_text($iter->get_parent()->get('titel'))))?></small>
</h2>
<p><?=sprintf(__('Fotoboek met %s en %s gemaakt op %s.'),
	__N('%d boek', '%d boeken', $iter->count_books()),
	__N('%d foto', '%d foto\'s', $iter->count_photos()),
	$iter->get('datum')) ?></p>
