<h1><?=__('Zoeken')?></h1>
<div class="messageBox search">
	<form method="get" action="search.php" class="search-widget">
		<label for="field-query"><?=__('Zoekopdracht')?></label>
		<input type="search" name="query" id="field-query" value="<?=markup_format_attribute($query)?>" placeholder="<?=__('Typ hier om te zoeken…')?>">
		<button type="submit" class="button"><?=__('Zoek')?></button>
	</form>

	<ul class="search-results">
		<?php foreach ($iter as $result): ?>
		<li data-search-relevance="<?=sprintf('%0.2F', $result->get_search_relevance())?>">
			<?php $this->render_partial('single_' . $result->get_search_type(), array('iter' => $result, 'query' => $query)) ?>
		</li>
		<?php endforeach ?>
	</ul>

</div>
