<h1><?=__('Zoeken')?></h1>
<div class="messageBox">
	<form method="get" action="search.php">
		<label for="field-query"><?=__('Zoekopdracht')?></label>
		<input type="search" name="query" id="field-query" value="<?=markup_format_attribute($query)?>">
		<button type="submit"><?=__('Zoek!')?></button>
	</form>

	<ul class="search-results">
		<?php foreach ($iter as $result): ?>
		<li>
			<?php $this->render_partial('single_' . $result->get_search_type(), array('iter' => $result, 'query' => $query)) ?>
		</li>
		<?php endforeach ?>
	</ul>

</div>
