<?php
$model = get_model('DataModelMailinglijst');
$mailinglijsten = $model->get_lijsten($iter->get_id());
?>
<h2><?= __('Mailinglijsten')?></h2>
<div class="list-group">
<?php foreach ($mailinglijsten as $lijst): ?>
	<div href="#" class="list-group-item list-group-item-with-action">
		<h4 class="list-group-item-heading">
			<a href="mailinglijsten.php?lijst_id=<?=$lijst->get('id')?>"><?= markup_format_text($lijst->get('naam')) ?></a>
			<small><?= markup_format_text($lijst->get('adres')) ?></small>
		</h4>

		<form class="list-group-item-action" method="post" action="mailinglijsten.php?lijst_id=<?=$lijst->get('id')?>">
			<input type="hidden" name="referer" value="profiel.php?lid=709&amp;tab=mailinglists">
			<?php if ($lijst->get('subscribed') && $model->member_can_unsubscribe($lijst)): ?>
				<input type="hidden" name="action" value="unsubscribe">
				<input type="submit" class="button" value="<?=__('Uitschrijven')?>">
			<?php elseif (!$lijst->get('subscribed') && $model->member_can_subscribe($lijst)): ?>
				<input type="hidden" name="action" value="subscribe">
				<input type="submit" class="button" value="<?=__('Aanmelden')?>">
			<?php endif ?>
		</form>

		<div class="list-group-item-text">
			<p><?= markup_parse($lijst->get('omschrijving')) ?></p>
		</div>
	</div>
<?php endforeach ?>
</div>
