<h2 id="wachtwoord"><?= __('Nieuw wachtwoord') ?></h2>
<form action="profiel.php?lid=<?= $iter->get('lidid') ?>#privacy" method="post">
	<?= input_hidden('submprofiel_wachtwoord', 'yes') ?>

	<table class="profiel">
		<tr>
			<td width="150"></td>
			<td></td>
		</tr>
		<?php if (!member_in_commissie(COMMISSIE_BESTUUR) && !member_in_commissie(COMMISSIE_KANDIBESTUUR)): ?>
		<?= table_row(label(__('Oud wachtwoord'), 'wachtwoord_oud', $errors) . ':', input_password('wachtwoord_oud')) ?>
		<?php endif ?>
		<?= table_row(label(__('Nieuw wachtwoord'), 'wachtwoord_nieuw', $errors) . ':', input_password('wachtwoord_nieuw')) ?>
		<?= table_row(label(__('Opnieuw'), 'wachtwoord_opnieuw', $errors) . ':', input_password('wachtwoord_opnieuw')) ?>

		<tr><td colspan="2" class="submit"><?= input_submit('subm', __('Wijzig wachtwoord')) ?></td></tr>
	</table>
</form>