<section class="personal-section">
	<h2><?= __('Persoonlijk') ?></h2>
	<?php foreach ($personal_fields as $field): ?>
		<?php $field_visibility = $model->get_privacy_for_field($iter, $field['name']) ?>
		<?php if ($field_visibility == DataModelMember::VISIBLE_TO_EVERYONE): ?>
			<div class="data-public">
				<?=label($field['label'], $field['name'])?>
				<span class="read-only"><?=markup_format_text($iter[$field['name']])?></span>
			</div>
		<?php elseif ($field_visibility == DataModelMember::VISIBLE_TO_MEMBERS): ?>
			<?php if (get_identity()->member_is_active() || get_identity()->member_in_committee(COMMISSIE_BESTUUR)): ?>
				<div class="data-members-only">
					<?=label($field['label'], $field['name'])?>
					<span class="read-only"><?=markup_format_text($iter[$field['name']])?></span>
					<i class="fa fa-lock" title="<?=__('Alleen zichtbaar voor ingelogde leden')?>"></i>
				</div>
			<?php endif ?>
		<?php elseif (get_identity()->member_in_committee(COMMISSIE_BESTUUR)): ?>
			<div class="data-private">
				<?=label($field['label'], $field['name'])?>
				<span class="read-only"><?=markup_format_text($iter[$field['name']])?></span>
				<i class="fa fa-eye-slash" title="<?=__('Privé')?>"></i>
			</div>
		<?php endif ?>
	<?php endforeach ?>
</section>

<?php if ($commissies = $this->get_commissies($iter)): ?>
<section class="committee-section">
	<h2 id="commissies"><?= __('Commissies') ?></h2>
	<p><?= markup_format_text(sprintf(__('%s is lid van de volgende commissies:'), member_first_name($iter, false, false))) ?></p>
	<ul>
		<?php foreach ($commissies as $commissie): ?>
		<li>
			<a href="show.php?id=<?=$commissie->get('page')?>"><?=markup_format_text($commissie->get('naam'))?></a>
			- <span class="functie"><?=markup_format_text(__translate_parts($commissie->get('functie'), ',/')) ?></span>
		</li>
		<?php endforeach ?>
	</ul>
</section>
<?php endif ?>