<?php
$personal_fields = [
	[
		'label' => __('Geboortedatum'),
		'name' => 'geboortedatum',
		'data' => [
			'geboortedatum' => format_date($iter->get('geboortedatum'))
		],
		'read_only' => true
	],
	[
		'label' => __('Beginjaar'),
		'name' => 'beginjaar',
		'read_only' => true
	],
	[
		'label' => __('Adres'),
		'name' => 'adres'
	],
	[
		'label' => __('Postcode'),
		'name' => 'postcode'
	],
	[
		'label' => __('Woonplaats'),
		'name' => 'woonplaats'
	],
	[
		'label' => __('Telefoonnummer'),
		'name' => 'telefoonnummer'
	],
	[
		'label' => __('E-Mail adres'),
		'name' => 'email'
	]
];
?>
<h1><?= sprintf(__('Profiel van %s'), markup_format_text(member_full_name($iter, false, false))) ?></h1>
<div class="messageBox clearfix">

	<?php if (isset($errors) && count($errors) > 0): ?>
	<div class="textCenter error-section">
		<p><span class="error"><?= __('Niet alle velden zijn goed ingevuld') ?></span></p>
		
		<?php if (isset($error_message)): ?>
		<p><?= str_replace("\n", "<br>\n", $error_message) ?></p>
		<?php endif ?>
	</div>
	<?php endif ?>

	<div class="tab-container">
		<div class="tab-sidebar">
			<?php $this->render_partial('profile_widget', compact('iter')) ?>
			<ul class="nav-tabs vertical">
				<li><a href="#personal"><?=__('Almanakgegevens')?></a></li>
				<li><a href="#profile"><?=__('Website')?></a></li>
				<li><a href="#privacy"><?=__('Privacy')?></a></li>
				<li><a href="#mailinglists"><?=__('Mailinglijsten')?></a></li>
				<li><a href="#sessions"><?=__('Sessies')?></a></li>
				<li><a href="#facebook"><?=__('Facebook')?></a></li>
			</ul>
		</div>

		<div class="tab-content">
			<div id="personal" class="tab-pane">
				<?php $this->render_partial('personal', compact('iter', 'errors', 'personal_fields')) ?>

				<?php if (member_in_commissie(COMMISSIE_BESTUUR) || member_in_commissie(COMMISSIE_KANDIBESTUUR)): ?>
					<?php $this->render_partial('visibility', compact('iter')); ?>
				<?php endif ?>
			</div>

			<div id="profile" class="tab-pane">
				<?php $this->render_partial('profile', compact('model', 'iter', 'errors')) ?>
				<?php if ($this->member_write_permission($iter)): ?>
					<?php $this->render_partial('password', compact('iter', 'errors')) ?>
				<?php endif ?>
			</div>
			
			<?php if ($this->member_write_permission($iter)): ?>
			<div id="privacy" class="tab-pane">
				<?php $this->render_partial('privacy', compact('model', 'iter')) ?>

				<a href="fotoboek.php?book=member_<?=$iter->get_id()?>"><?=markup_format_text(sprintf(__('Foto\'s van %s'), member_full_name($iter, false, false))) ?></a>
			</div>
			<?php endif ?>
			
			<?php if ($this->is_current_member($iter) || member_in_commissie(COMMISSIE_EASY)): ?>
			<div id="mailinglists" class="tab-pane">
				<?php $this->render_partial('mailinglists', compact('iter')) ?>
			</div>
	
			<div id="sessions" class="tab-pane">
				<?php $this->render_partial('sessions', compact('iter')) ?>
			</div>
			<?php endif ?>

			<?php if($this->is_current_member($iter->get('lidid')) && get_config_value('enable_facebook_rsvp', false)): ?>
			<div id="facebook" class="tab-pane">
				<?php $this->render_partial('facebook', compact('iter')) ?>
			</div>
			<?php endif ?>
		</div>
	</div>
	
	<!-- To be moved to a read-only version of a persons profile? -->
	<?php if ($commissies = $this->get_commissies($iter)): ?>
	<div class="floatLeft almanak">
		<h2 class="profilehead" id="commissies"><?= __('Commissies') ?></h2>
		<p><?= markup_format_text(__('Lid van de volgende commissies:')) ?></p>
		<ul>
			<?php foreach ($commissies as $commissie): ?>
			<li>
				<a href="show.php?id=<?=$commissie->get('page')?>"><?=markup_format_text($commissie->get('naam'))?></a>
				- <span class="functie"><?=markup_format_text(__translate_parts($commissie->get('functie'), ',/')) ?></span>
			</li>
			<?php endforeach ?>
		</ul>
	</div>
	<?php endif ?>
</div>

<script>
jQuery(function($) {
	// Hide all tabs
	$('.tab-pane').hide();

	$('.nav-tabs').on('click', 'a[href^=#]', function(e) {
		e.preventDefault();
		
		// Hide all other tabs
		$('.tab-pane').hide();

		// Show this tab
		$($(this).attr('href')).show();

		// Mark all other tabs as inactive
		$('.nav-tabs li').removeClass('active');

		// Except for this one
		$(this).closest('li').addClass('active');
	});
})
</script>