<h1> <?= __('Commissies') ?></h1>
<div class="messageBox">
	<ul class="commissie-index">
	<?php foreach ($iter as $commissie): ?>
		<li class="commissie">
			<?php if ($commissie->get('vacancies')): ?>
			<span class="vacancy-badge"><?=__('Commissieleden gezocht!')?></span>
			<?php endif ?>
			<a href="commissies.php?commissie=<?= rawurlencode($commissie->get('login')) ?>" class="link">
				<?php if ($imgpath = $this->get_commissie_thumb($commissie)): ?>
					<img src="<?=markup_format_attribute($imgpath, ENT_QUOTES)?>" class="thumbnail">
				<?php endif ?>
				<span class="overlay">
					<span class="name"><?= markup_format_text($commissie->get('naam')) ?></span>
					<span class="summary"><?= $this->get_summary($commissie) ?></span>
				</span>
			</a>
		</li>
	<?php endforeach ?>
	</ul>
</div>
