<div class="pageHeading">
	<?php if (get_policy($model)->user_can_create()): ?>
		<div class="controls inline"><a href="<?=$controller->link_to_create()?>" class="create-link"><?= __('Nieuwe commissie') ?></a></div>
	<?php endif ?>
	<h1><?= __('Commissies') ?></h1>
</div>
<div class="messageBox">
	<?php if (get_config_value('committee_battle', false)): ?>
		<?php
		$committee_photos = array_map(getter('thumbnail'), $iter);
		$committee_photos = array_values(array_filter($committee_photos));
		?>
		<a href="committeebattle.php">
			<div class="promotional-banner committee-battle-banner" data-photos="<?=markup_format_attribute(json_encode($committee_photos)) ?>">
				<h1><?=__('Committee Battle') ?></h1>
			</div>
		</a>
	<?php endif ?>
	<ul class="commissie-index">
	<?php foreach ($iter as $commissie): ?>
		<li class="commissie">
			<a href="<?=$controller->link_to_read($commissie)?>" class="link">
				<?php if ($imgpath = $this->get_commissie_thumb($commissie)): ?>
					<img src="<?=markup_format_attribute($imgpath, ENT_QUOTES)?>" class="thumbnail">
				<?php endif ?>
				<span class="overlay">
					<span class="name"><?= markup_format_text($commissie->get('naam')) ?></span>
					<span class="summary"><?= $this->get_summary($commissie) ?></span>
				</span>
			</a>
			<?php if ($commissie->get('vacancies')): ?>
				<span class="vacancy-badge"><?=__('Commissieleden gezocht!')?></span>
			<?php endif ?>
		</li>
	<?php endforeach ?>
	</ul>
</div>
