<?php
$editable = new ControllerEditable($iter->get('page'));
?>

<div class="pageheading">
	<?php if($editable->user_can_update()): ?>
	<div class="controls inline">
		<a href="<?=markup_format_attribute($editable->link_to_update()) ?>"><?= image('edit.png', __('bewerken'), __('Pagina bewerken'))?></a>
	</div>
	<?php endif ?>
	<h1><?= markup_format_text($iter->get('naam')) ?></h1>
</div>

<div class="messageBox">
	<?php
	if ($iter->get('vacancies'))
		$this->render_partial('leden_gezocht', compact('model', 'iter'));
	?>

	<?php $this->render_partial('foto', compact('model', 'iter')) ?>

	<?php $editable->run() ?>

	<?php $this->render_partial('leden', compact('model', 'iter')) ?>

	<?php $this->render_partial('agenda', compact('model', 'iter')) ?>
</div>
