homepage:
  path: /
  controller: App\Controller\HomepageController

page:
  path: /page
  controller: App\Controller\PageController

profile_picture:
  path: /profile_picture
  controller: App\Controller\ProfilePictureController

sessions:
  path: /sessions
  controller: App\Controller\SessionsController

stickers:
  path: /stickers
  controller: App\Controller\StickersController


legacy:
  path: /{name}.php
  controller: App\Controller\LegacyController
  defaults:
    map:
      index:
        controller: App\Controller\HomepageController
        parameters: { _route: homepage }
      foto:
        controller: App\Controller\ProfilePictureController
        parameters: { _route: profile_picture }
      sessions:
        controller: App\Controller\SessionsController
        parameters: { _route: sessions }
      show:
        controller: App\Controller\PageController
        parameters: { _route: page }
      stickers:
        controller: App\Controller\StickersController
        parameters: { _route: stickers }
