<!DOCTYPE html>
<html>
	<head>
		<title>Cover Newsletter Editor</title>
		<style>
		body {
			font: 16px/24px sans-serif;
			background: #ccc;
		}

		.login-container {
			width: 300px;
			padding: 20px;

			background: white;

			margin: 100px auto;
			border-radius: 4px;
		}

		.login-container p {
			margin: 0 0 16px 0;
		}

		.login-container label {
			font-weight: bold;
		}

		.login-container input {
			width: 290px;
			font: inherit;
			padding: 4px;
			margin: 0 0 16px 0;
			border: 1px solid silver;
			border-radius: 4px;
		}

		.login-container button {
			width: 300px;

			font: inherit;

			padding: 6px 12px;
			color: #333;
			background-color: #fff;
			text-align: center;
			cursor: pointer;
			border: 1px solid #ccc;
			border-radius: 4px;
			-webkit-user-select: none;
		}

		.login-container button:hover {
			background-color: #ebebeb;
			border-color: #adadad;
		}

		</style>
	</head>
	<body>
		<div class="login-container">
			<form method="post">
				<p>Log in with your email and password from the Cover website.</p>

				<label for="email">email address:</label>
				<input type="email" name="email" autofocus>

				<label for="password">Password:</label>
				<input type="password" name="password">

				<button type="submit">Log in</button>
			</form>
		</div>
	</body>
</html>