<?php
$e = isset($errors) ? $errors : null;

$days = range(0, 31);
unset($days[0]);

$months = get_months();
unset($months[0]);

require_once 'include/controllers/ControllerEditable.php';

$voorwaarden = new ControllerEditable('Voorwaarden aanmelden');

$opmerkingen = new ControllerEditable('Opmerkingen aanmelden');

?>
<h1><?= __('Lidmaatschapsformulier') ?></h1>
<div class="messageBox">
	<?php if ($voorwaarden->user_can_update()): ?>
	<div class="controls inline">
		<a href="<?=markup_format_attribute($voorwaarden->link_to_update()) ?>" class="edit-link"><?=__('Bewerk voorwaarden')?></a>
	</div>
	<?php endif ?>
	<h2><?= __('Voorwaarden') ?></h2>
	<?php $voorwaarden->run(); ?>

	<?php if (!empty($message)): ?>
	<div class="message"><?= $message ?></div>
	<?php endif ?>

	<?php if ($e): ?>
	<div class="error-section">
		<p><?= __('Niet alle velden zijn goed ingevuld') ?></p>
	</div>
	<?php endif ?>

<form method="post" action="lidworden.php" class="new-member-form"><?= input_hidden('submlidworden', 'yes') ?>
<table>

	<tr>
		<th colspan="2"><?=__('Naam')?></th>
	</tr>

	<?=$this->render_text_row(__('Voornaam'), 'voornaam', $e, true) ?>
	<?=$this->render_text_row(__('Tussenvoegsel'), 'tussenvoegsel', $e, false, 'class', 'small') ?>
	<?=$this->render_text_row(__('Achternaam'), 'achternaam', $e, true) ?>

	<?= table_row(label(__('Gender'), 'gender', $e, true),
		select_field('gender', array(
			'm' => __('Man'),
			'f' => __('Vrouw'),
			'o' => __('Anders')
		), null))  ?>

	<tr>
		<th colspan="2"><?=__('Adres')?></th>
	</tr>

	<?=$this->render_text_row(__('Straatnaam + Huisnummer'), 'adres', $e, true) ?>
	<?=$this->render_text_row(__('Postcode'), 'postcode', $e, true, 'class', 'small') ?>
	<?=$this->render_text_row(__('Woonplaats'), 'woonplaats', $e, true) ?>

	<tr>
		<th colspan="2"><?=__('Contact')?></th>
	</tr>

	<?=$this->render_text_row(__('Telefoonnummer'), 'telefoonnummer', $e, false) ?>
	<?=$this->render_text_row(__('E-Mail adres'), 'email', $e, true) ?>

	<?= table_row(label(__('Geboortedatum'), 'geboortedatum', $e, true), 
		  select_field('day', $days, null) . ' ' .
		  select_field('month', $months, null) . ' ' .
		  input_text('year', null, 'maxlength', 4, 'size', 3,
			     'class', 'small', 'placeholder', 1990)) ?>

	<tr>
		<th colspan="2"><?=__('Studie')?></th>
	</tr>

	<?=$this->render_text_row(__('Studentnummer'), 'studentnummer', $e, true, 'placeholder', 's') ?>
	<?=$this->render_text_row(__('Studierichting'), 'studierichting', $e, true) ?>
	<?= table_row(label(__('Fase'), 'fase', $e, true), select_field('fase', array('b' => __('Bachelor'), 'm' => __('Master'), 'o' => __('Anders')), null))  ?>

	<tr>
		<th colspan="2"><?=__('Betaling')?></th>
	</tr>

	<?=$this->render_text_row(__('IBAN'), 'rekening', $e, true, 'size', 30) ?>

	<?=$this->render_text_row(__('BIC'), 'bic', $e, true, 'size', 30, 'placeholder', __('Alleen nodig indien buitenlandse bank')) ?>
	<tr>
		<td></td>
		<td><?=__('Een BIC nummer is alleen noodzakelijk bij een niet-Nederlands banknummer.')?></td>
	</tr>

	<?= table_row(label('Machtiging', 'machtiging', $e, true), '<label>' . input_checkbox('machtiging', null) . ' ' . __('Ik machtig hierbij Cover om 1x per jaar de contributie automatisch van mijn rekening af te schrijven (verplicht)') . '</label>') ?>

	<tr>
		<th colspan="2"><?=__('Mailing')?></th>
	</tr>

	<?= table_row(label('Mailing', 'mailing', $e, false), '<label>' . input_checkbox('mailing', null) . ' ' . __('Ik wil graag e-mails over activiteiten van Cover ontvangen. (Dit wil je. Daarnaast, uitschrijven kan gemakkelijk via de website.)') . '</label>') ?>

	<tr>
		<th colspan="2"></th>
	</tr>

	<?=$this->render_text_row(__('Wat is de kleur van gras? (ik ben geen bot)'), 'spam', $e, true) ?>

	<tr>
		<td></td>
		<td><?=__("Als je het niet zeker weet, vul dan 'groen' in.")?></td>
	</tr>

	<tr>
		<td class="submit" colspan="2"><br>
		<br>
		<?= input_submit('subm', __('Aanvraag versturen')) ?></td>
	</tr>
</table>
</form>

	<?php if ($opmerkingen->user_can_update()): ?>
	<div class="controls inline">
		<a href="<?=markup_format_attribute($opmerkingen->link_to_update()) ?>" class="edit-link right"><?=__('Bewerk opmerkingen')?></a>
	</div>
	<?php endif ?>
	<h2><?= __('Opmerkingen') ?></h2>
	<?php $opmerkingen->run(); ?>
</div>
