<?php

$search_link = function($conditions) {
	$url = 'https://secretary.svcover.nl/administration/everyone/?' . http_build_query($conditions);
	return sprintf('<a href="%s" target="_blank" title="Search for this in Secretary"><img src="themes/default/images/search.png" width="12" height="12"></a>', markup_format_attribute($url));
};

?>
<div class="messageBox">
	<?php if ($message): ?>
		<p><?=$message?></p>
	<?php endif ?>
	<p>After a new student signs up for Cover through the online registration form, they have to confirm their email address. Until they clicked the link in the confirmation email that was send when they finished filling in the form, their registration is stuck here.</p>
	<p>Unfortunately, not everyone confirms their email address, and some don't even receive the initial confirmation mail. That is why this page exists. Here you can take one of the following steps:</p>
	<p><strong>Before you do any of these steps, please confirm that the student didn't already finish their registration at a different moment by checking <a href="https://secretary.svcover.nl/" target="_blank">Secretary</a>.</strong></p>
	<ol>
		<li>Re-send the confirmation email</li>
		<li>Copy the link from the confirmation email. With that link, you can either</li>
		<ol>
			<li>Use the email address mentioned here to send them a personal mail with the link so they can click it</li>
			<li>Copy &amp; paste the link yourself in your browser to confirm <em>their</em> registration.</li>
		</ol>
		<li>Delete a registration when a the person is already a member (e.g. they finished their registration at a different moment)</li>
		<li>Delete duplicate registrations (note that the links in the confirmation emails for those registrations then won't work any more)</li>
	</ol>
</div>

<h1><?= __('Hangende aanmeldingen')?></h1>
<div class="messageBox">
	<form method="post" action="">
		<table class="full-width-table">
			<col>
			<col>
			<col>
			<col>
			<thead>
				<tr class="header">
					<th></th>
					<th><?= __('Naam') ?></th>
					<th><?= __('Email') ?></th>
					<th><?= __('Aangemeld op') ?></th>
					<th><?= __('Bevestigingslink') ?></th>
				</tr>
			</thead>
			<tbody>
			<?php foreach ($iter as $row): ?>
					<tr>
						<td><input type="checkbox" name="confirmation_code[]" value="<?=markup_format_attribute($row['confirmation_code'])?>"></td>
						<td>
							<?= markup_format_text(format_string('$first_name$family_name_preposition|optional $family_name', $row['data'])) ?>
							<?= $search_link(['full_name' => format_string('$first_name$family_name_preposition|optional $family_name', $row['data'])]) ?>
						</td>
						<td>
							<?= markup_format_text($row['data']['email_address']) ?>
							<?= $search_link(['full_name' => '', 'email_address' => $row['data']['email_address']]) ?>
						</td>
						<td><?= format_date($row['registered_on']) ?></td>
						<td><input type="text" value="<?=markup_format_attribute(sprintf('https://www.svcover.nl/lidworden.php?confirmation_code=%s', urlencode($row['confirmation_code'])))?>"></td>
					</tr>
			<?php endforeach ?>
			</tbody>
		</table>
		<div class="controls">
			<button name="action" value="resend" class="button">Resend confirmation mail</button>
			or <button name="action" value="delete" class="button">Cancel registrations</button>
			of all the selected names
		</div>
	</form>
</div>